### ISSUE TITLE
intellij gitignore template is incorrect

### ISSUE THREAD

**Issue by philipmjohnson** [joeblau/gitignore.io#104]
According to the official intelliJ documentation (https://intellij-support.jetbrains.com/entries/23393067), the gitignore generated by gitignore.io is incorrect.  It ignores the entire .idea directory, which is the wrong default.  To fix this, please change the top of the file to:

     ## Directory-based project format:
     # .idea/
     
     # User-specific stuff:
     .idea/workspace.xml
     .idea/tasks.xml
     .idea/dictionaries

**Comment by joeblau** [comment]
Intellij is an alias from the `JetBrains.gitignore` template which is maintained at [GitHub's official repository](https://github.com/github/gitignore/blob/408c616ae0ad8f4b8101d8e876b9b67ac6b14059/Global/JetBrains.gitignore) and [referenced though a submodule](https://github.com/joeblau/gitignore.io/tree/master/data).  You can submit a bug or a PR on GitHub's official repository or just edit the file you need manually as you've done.

**Comment by philipmjohnson** [comment]
OK, just opened a PR.

**Comment by volkertb** [comment]
This change disregards and inconveniences the majority of us Java developers who use IDE-independent build systems such as Maven or Gradle. I opened a separate issue for this: #360
