### ISSUE TITLE
gen-external-apklibs missing under Android

### ISSUE THREAD

**Issue by DaRolla** [joeblau/gitignore.io#106]
Hi,

unfortunately the generated folder 'gen-external-apklibs' is missing for 'Android' as well as 'IntelliJ'

Thanks for your nice project,
Marco

**Comment by joeblau** [comment]
You'll want to file these under https://github.com/github/gitignore.

If they don't accept the changes, we can add them as a .patch which we can use to extend the main libraries.

**Comment by joeblau** [comment]
Added file to `.patch` ignore
