### ISSUE TITLE
Nested maven projects

### ISSUE THREAD

**Issue by tgkprog** [joeblau/gitignore.io#111]
Nested maven projects need entry:

**/target

Else sub projects targets are not ignored.

**Comment by joeblau** [comment]
This fix should be submitted to the main GitHub gitignore repository: https://github.com/github/gitignore.  My project just references that though a submodule.  If you strongly strongly believe it should be included sooner, you can also create a .patch file which will append a patch to the original Maven.template.

**Comment by tgkprog** [comment]
Okay thanks for letting me know.
