### ISSUE TITLE
Horizontal scrolling for /docs 

### ISSUE THREAD

**Issue by zcei** [joeblau/gitignore.io#116]
Hej,

I just found this project and while reading the docs on my machine (MacBook Pro 13" Retina) some commands exceed the horizontal width of my screen.

Currently there is no possibility to scroll to the right to get the rest of the command.

You can highlight the beginning and `alt + arrow-right` to the end, but then you'll end up with breaking the whole functionality of the page as you can't "scroll back".

Couldn't this be done by an `overflow` in CSS?

Best,
zcei

**Comment by joeblau** [comment]
Two finger swipe left and right is scrolling horizontally on a Mac.
![Two Finger Swipe Left](http://www.yourmaccafe.com/tips/files/ht4721-notification_center-003-en.png)

**Comment by zcei** [comment]
Nope, just tried it out, it's due to Chrome.
Safari can do it properly, but you still should think about a fix for Chrome - someone told me, a few people use it on a daily base :wink:

**Comment by joeblau** [comment]
Alrighty.  I'll have to look into a replacement for Flatdoc then.  I had a few issues originally, and while I think it looks good, it obviously has some usability issues.  Thanks for catching this and also if you have any suggestions, I'd appreciate them.

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/rstacruz/flatdoc/issues/40

**Comment by dragon788** [comment]
I mostly read the code when I'm looking for how to use things, but I glanced at the docs pages and was also seeing this in Chrome. On a 4K screen at native resolution I could see pretty much everything, but if I zoomed in at all to make reading more comfortable things started getting cut off.

**Comment by joeblau** [comment]
I'm looking for a better Markdown documentation template render plugin, but I haven't found anything.  I was tempted to make my own, but I haven't had the chance to get around to it yet.
