### ISSUE TITLE
Windows instructions not clear

### ISSUE THREAD

**Issue by Tri125** [joeblau/gitignore.io#117]
1. On docs: Script for Powershell v2, Powershell v3, alternative for msysgit (for curl.cmd) and gi.cmd are all together and looks like they are all part of the same script.
2. Under the "Global" section, the use of "gig" is recommended for windows. gig is the function name for the Powershell v2 and v3 script, I fail to see "gig" under the msysgit alternative. Is gig meant only if you choose the Powershell scripts and not just about Windows?
3. ~~Following the instructions doesn't make it functional.~~ (Upon investigation, this was a problem with curl itself).

**Comment by Tri125** [comment]
About 3. I think this is an issue with curl shipped with git for windows (1.9.5) or how the website handle things. I enabled verbose and I got an handshake error. curl (35) error.

**Comment by Tri125** [comment]
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

I found the following on the matter : 
* https://github.com/msysgit/git/issues/325

* http://help.directadmin.com/item.php?id=534

Git-1.9.5-preview20150319 updated Curl to 7.41.0, same issue on this version (latest).

**Comment by Tri125** [comment]
On linux I ran
     curl -L -Iv https://www.gitignore.io/api/android

I got:
     SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256

Git on windows use OpenSSL 0.9.8zf 19 Mar 2015

Back on Windows, openssl ciphers in common is only AES128.

     curl -L -v --ciphers AES128 https://www.gitignore.io/api/android
     failed setting cipher list: AES128

On linux:

     curl -L -v --ciphers AES128 https://www.gitignore.io/api/android
works.

This is clearly an issue with Git on windows and not of unclear instructions or the ciphers used on the website.

**Comment by joeblau** [comment]
Thanks for taking a look at this.  I haven't had a windows machine for over 4 years so the instructions I posted were what someone else claimed to have working.  I can update the instructions based on your findings.

**Comment by Tri125** [comment]
Here you should see that from /docs the information is difficult to read.

![image](https://cloud.githubusercontent.com/assets/2048645/7601797/6005b13e-f8e9-11e4-84d9-7cf8f2340212.png)

The mention of using "gig if you are on windows" is only if you used the PowerShell script alternative.
I haven't used this method to achieve a working solution on windows, so I will not comment about it.

As explained, you do not need the PowerShell script if you have curl installed (bundled with msysgit) and the cmd script will work (the third one under Windows). However, while I was able to call gi from the command prompt, I wasn't able under msysgit. I haven't investigated, but it's was most likely a problem with the PATH on my own system (msysgit complaining that it can't find it).

There is an alternative, if you want to be able to call gi only with msysgit. You don't do anything under the Windows section, you add 

     function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

In your .bashrc file located under HOME. ie: C:\Users\myUsername

Notice the missing backslash before $. I'm not proficient enough about bash to know what's going on, but msysgit was complaining about it.

Unfortunately, and as you noticed in my comments above, I found that the current versions of msysgit (Git-1.9.5-preview20150319) ship with curl 7.41.0 which have a problem setting the ciphers, which render it useless with ssl(?).

In order to make it work, windows users will either have to manually download curl 7.42.0 (winssl) and replace it with the one located under the git installation folder: \Git\bin or install Git for Windows 2.4.0 release 2 (latest release) which is the new replacement for msysgit, but not currently intended for use in production (they haven't officially moved from msysgit to Git for Windows yet).

Phew.

**Comment by Tri125** [comment]
Oh, and why not explaining what the command under the Git section does? 

Not everyone is proficient with alias and I'm sure it would beneficial just to say that "This command add a global alias to git to use git. Write" git ignore" to call it. 
Something like that.

**Comment by joeblau** [comment]
I'm going to close this.  I haven't received any other feedback about this and I don't use Windows so I don't know what the best instructions *should* be.  If you want to submit a pull request with suggested changes, I'll be happy to merge them in.
