### ISSUE TITLE
Migrate off of Kraken.js to Golang

### ISSUE THREAD

**Issue by joeblau** [joeblau/gitignore.io#124]
This tool is good in principle, but it's plagued with [bugs](https://github.com/krakenjs/kraken-js/issues/381) that don't allow the system to keep up to date with the latest dependencies.

Looking into migrating to golang.

**Comment by aredridel** [comment]
Fixed the bug in the generator, and there is a release of makara that supports dust 2.7 now.

**Comment by joeblau** [comment]
:+1: I just saw! Thanks!

**Comment by joeblau** [comment]
Sticking with Kraken.
