### ISSUE TITLE
MODX is missing

### ISSUE THREAD

**Issue by bertoost** [joeblau/gitignore.io#125]
MODX configuration is simple (by default);

/core/cache/*
!/core/cache/.gitkeep

Maybe some more @Mark-H ?

**Comment by Mark-H** [comment]
Maybe `/core/packages/*/*` too? Really depends on how you version your MODX site..

**Comment by bertoost** [comment]
Indeed. Maybe with some comments .. 
Also /core/import/* and /core/export/*
