### ISSUE TITLE
SSLV3 handshake failure

### ISSUE THREAD

**Issue by idursun** [joeblau/gitignore.io#131]
I get empty result when I invoke git ignore from command line in git bash on windows.

Running

```curl -L https://www.gitignore.io/api/scala,windows```

prints the following to the console:

```error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure```

FYI, it used to work in the past.

**Comment by joeblau** [comment]
Which version of Windows are you running?

Can you also run `curl -vvv -L https://www.gitignore.io/api/scala,windows` show me the output?

**Comment by idursun** [comment]
Hi,

output is:
```
*   Trying 104.28.0.76...
* Connected to www.gitignore.io (104.28.0.76) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Program Files (x86)\git\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.0, TLS handshake, Client hello (1):
* TLSv1.0, TLS alert, Server hello (2):
* error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by joeblau** [comment]
Ah hah.  So my CDN is Cloudflare and the disable SSLv3 due to POODLE vulnerability[1].  You'll need to disable SSLv3 support in order to access the url via curl. I wouldn't want to subject all of the users gitignore.io to this potential vulnerability.

[1] - https://blog.cloudflare.com/sslv3-support-disabled-by-default-due-to-vulnerability/

**Comment by hglattergotz** [comment]
The way I fixed this on El Capitan is to install a newer version of cUrl via brew. The version that ships with OSX does not work with cloudflair.

**Comment by joeblau** [comment]
Hm.. I've never had to do that but if that worked for your, thanks for figuring that out.

**Comment by hglattergotz** [comment]
What options do you use to get it to work with the default installation? I
could not make it work.
On Sat, Feb 27, 2016 at 16:45 Joe Blau <notifications@github.com> wrote:

> Hm.. I've never had to do that but if that worked for your, thanks for
> figuring that out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeblau/gitignore.io/issues/131#issuecomment-189670663>
> .
>
-- 
Henning Glatter-Götz
henning@glatter-gotz.com
+49 176 64786830

**Comment by joeblau** [comment]
I'm using `curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5` and it works for me.

**Comment by hglattergotz** [comment]
The version of curl that is installed with the OS (El Capitan) is `7.38.0` and that does not work for me.
Installing with brew brought it up to `7.47.1` and that works.
