### ISSUE TITLE
Support for the R programming language

### ISSUE THREAD

**Issue by b-long** [joeblau/gitignore.io#136]
I don't know if this is the right place to ask, but you should support R!  GitHub does with their generator : https://github.com/github/gitignore/blob/master/R.gitignore

**Comment by joeblau** [comment]
It's actually supported, but the not though the UI due to a sorting error.  I'll keep this issue open until I have some time to triage it.

https://www.gitignore.io/api/r

**Comment by b-long** [comment]
:+1: Ah, fair enough.  Sorry I didn't notice that.  Thanks for all your efforts :smile:

**Comment by joeblau** [comment]
I've also fixed the API so R shows up in the proper order... the old sorting algorithm wasn't alphabetized.

**Comment by b-long** [comment]
Very nice.

**Comment by joeblau** [comment]
@b-long Okay, had a nightmare updating because of some Kraken stuff, but if you go check now and type `R` it shows up as the second result behind RubyMine.

**Comment by b-long** [comment]
Fantastic, I see it is working.  After typing `R`, I needed to scroll to see "R", but that's fine by me!  Then, I added Python and created a `.gitignore` file.  Of course, this is also available via the [API](https://www.gitignore.io/api/r,python), but for posterity the output is below.  Thanks again :+1:  

```

# Created by https://www.gitignore.io/api/r,python

### R ###
# History files
.Rhistory
.Rapp.history

# Session Data files
.RData

# Example code in package build process
*-Ex.R

# RStudio files
.Rproj.user/

# produced vignettes
vignettes/*.html
vignettes/*.pdf

# OAuth2 token, see https://github.com/hadley/httr/releases/tag/v0.3
.httr-oauth


### Python ###
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*,cover
.hypothesis/

# Translations
*.mo
*.pot

# Django stuff:
*.log

# Sphinx documentation
docs/_build/

# PyBuilder
target/
```
