### ISSUE TITLE
Carthage build folder ignored in Swift template by default

### ISSUE THREAD

**Issue by robnadin** [joeblau/gitignore.io#137]
So I've noticed in the Swift template:
https://www.gitignore.io/api/swift

The `Carthage/Build` line is added by default. Ignored the builds folder is NOT recommended as when following the steps to install Carthage on their GitHub page it specifically describes how to embed the frameworks into the project by referencing them from inside the builds folder.

**Comment by joeblau** [comment]
Yeah, This Swift file is a symlink to the [Objective-C](https://www.gitignore.io/api/objective-c) template.  Maybe I should unbundle them or remove the symlink.  The Objective-C template is maintained by GitHub at https://github.com/github/gitignore/blob/master/Objective-C.gitignore.  If you think there should be some changes I would submit a PR to their repo and when I do my next update, the changes will be merged in.

**Comment by joeblau** [comment]
I've been using carthage for a few projects and ignoring the `Carthage/Build` directory is the correct process.  You don't want to include binaries in your repository which are exactly what are contained in the `Carthage/Build` folder.  If you download a new project, you should run `cartage update ` an then all of your links will be correct in your Swift project.
