### ISSUE TITLE
Copyright information

### ISSUE THREAD

**Issue by mgmax** [joeblau/gitignore.io#155]
The used gitignore files are MIT-licensed: https://github.com/github/gitignore/blob/master/LICENSE
This means that the output must not be used without including copyright information and the license text (or maybe a link to it).

**Comment by joeblau** [comment]
MIT License is included at the footer of the README.md.  If you want to make a separate LICENSE file, that works as well.

**Comment by mgmax** [comment]
I did not mean your code, but the output of the program. People will just copy-and-paste it, not knowing they violate the license of the used gitignore snippets. 
The license essentially says "all reproductions must include a copy of this license".
A workaround would be to at least include a line like:
`# Created from a template (C) github.com, see https://github.com/github/gitignore/blob/master/LICENSE for license details`

**Comment by joeblau** [comment]
GitHub doesn't include the license in their files, nor do they include it when you use their pre-generated templates built from this repository.  I'm not a lawyer so I don't claim to know any more than just reading the license, but it doesn't seem bundled with their software.  Or are you suggesting that when user manually copies any template from GitHub's repo, they are supposed to manually add that reference into their .gitingore file as well?

**Comment by joeblau** [comment]
Adding this logic is going to add considerable complexity to this system.  Unless this is pressing, I'm going to close this.

**Comment by mgmax** [comment]
you're completely right with your comment regarding GitHub's usage of the files. I mailed their support, let's see what they tell me.

**Comment by mgmax** [comment]
GitHub support told me: "If you use a few of the .gitignore files you will won't need to worry about attribution!"
So this is no problem for you, as long as they don't change their mind.

**Comment by joeblau** [comment]
@mgmax Thanks a lot for looking into this.
