### ISSUE TITLE
gi list using newline rather comma

### ISSUE THREAD

**Issue by pandada8** [joeblau/gitignore.io#156]
make it more readable

**Comment by joeblau** [comment]
If it's displayed with a new line, the list will be extremely long and it will most likely scroll the terminal past whatever you're looking for.

**Comment by hashhar** [comment]
We can draw it up in columns, couldn't we? I'll try making a pull request.

**Comment by hashhar** [comment]
Kind of like how `menu-complete` works in bash.

**Comment by joeblau** [comment]
I haven't used `menu-complete` so I'll have to take a look at it.  Just remember that the output has to render correctly in every shell on every operating system :).  There is a bit of added complexity and testing if we're going to add new lines and tabs.  Is there a way to pipe data to menu complete if it's formatted in a certain way?  I feel like that would fall more in line with the Unix philosophy.

**Comment by joeblau** [comment]
I was playing with formatting and I made a change to make the output look like this

```
actionscript,ada,agda,alteraquartusii,android
anjuta,appbuilder,appceleratortitanium,appcode,appengine
archives,archlinuxpackages,assembler,atmelstudio,autotools
basercms,basic,bazel,bitrix,bluej
bower,bricxcc,c,c++,cakephp
carthage,ceylon,cfwheels,chefcookbook,clojure
cloud9,cmake,code,codeblocks,codeigniter
codeio,codekit,coffeescript,commonlisp,composer
concrete5,coq,craftcms,crashlytics,crystal
cuda,cvs,d,dart,darteditor
delphi,django,dm,dotsettings,dreamweaver
dropbox,drupal,eagle,easybook,eclipse
```

Then when you run `gi list  | column -ts ","` You get a nice column formatted output:
<img width="669" alt="screen shot 2016-02-16 at 6 49 16 am" src="https://cloud.githubusercontent.com/assets/1218847/13075489/7dd31744-d479-11e5-9f53-3262722f9d54.png">

The only thing I don't 100% like is the formatting got the five items per line.

**Comment by pandada8** [comment]
looks perfect ！

Joe Blau <notifications@github.com>于2016年2月16日周二 下午7:50写道：

**Comment by joeblau** [comment]
`gi list | column -ts ","` now works.

**Comment by adjohnson916** [comment]
See also #160 which was merged & released and introduced an API for line-separated and JSON formats.

Accessed via:
* https://www.gitignore.io/api/list?format=lines
* https://www.gitignore.io/api/list?format=json

Or the CLI e.g.:
* `gi list?format=json`
* `gi list?format=lines`
