### ISSUE TITLE
ignore more than you want?!

### ISSUE THREAD

**Issue by lorinczelod** [joeblau/gitignore.io#158]
I generated the following from gitignore.io for the prestashop.
```
### Prestashop ###
...
# The following folders contain product images, virtual products, CSV's, etc.
...
img/  
...
```
I think, the img is intended to ignore the root img folder, but it ignores all img folder, e.g. the admin/filemanager/img/ too.
So my proposal is to set the root when it is this kind of case:
/img/

**Comment by joeblau** [comment]
This bug is fixed in the latest main branch: https://github.com/github/gitignore/blob/master/Prestashop.gitignore.  I will merge in the changes and fix this locally right now.
