### ISSUE TITLE
Improve CTA And First Landing Page Experience

### ISSUE THREAD

**Issue by joeblau** [joeblau/gitignore.io#163]
What you could do is have a bit more of an extensive splash page. Explain the problem, why people should use your gitignore file, why it’s better than just swinging it, etc etc. That might help for your google results.

Another tip - while you're writing up that content, think about what someone will search for.  What would someone put into Google to find you. Make sure that wording is on the page. Use Google's autocomplete to get other phrases to use.

**Comment by BookOfGreg** [comment]
Do you have some info from webmaster tools? Would be interesting to see what other pages come up for the common search terms for this tool. Might guide the content for the homepage.

**Comment by joeblau** [comment]
I can give you access if you want to take a look at it.  Just don't break anything :smile:

**Comment by joeblau** [comment]
Here are some metrics if. you want to take a look
<img width="926" alt="screen shot 2017-01-29 at 11 07 21 pm" src="https://cloud.githubusercontent.com/assets/1218847/22411993/de8a9c68-e677-11e6-9734-37f8b6c96f0d.png">

[www-gitignore-io_20170130T040638Z_SearchAnalytics.txt](https://github.com/joeblau/gitignore.io/files/738135/www-gitignore-io_20170130T040638Z_SearchAnalytics.txt)

**Comment by joeblau** [comment]
I'm going to close this for now — based on speaking with my designer, the goal is going to be to keep the home page clean.
