### ISSUE TITLE
https://www.gitignore.com/api/ has security error

### ISSUE THREAD

**Issue by imju** [joeblau/gitignore.io#164]
When I access the api site in browser(Chrome), I got security exception like following.  You may want to check on your ssl setup. 

Your connection is not private

Attackers might be trying to steal your information from www.gitignore.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID
  Automatically report details of possible security incidents to Google. Privacy policy
Back to safetyHide advanced
This server could not prove that it is www.gitignore.com; its security certificate is from *.domainmarket.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by joeblau** [comment]
Which version of Chrome are you using?

**Comment by imju** [comment]
47.0.2526.106 (64-bit)
I think it maybe something to do with cert.

**Comment by joeblau** [comment]
The problem might be that you have expired certificates in your keychain trust store.  Try these steps: http://apple.stackexchange.com/questions/134601/chrome-showing-the-sites-security-certificate-is-not-trusted-for-github

**Comment by imju** [comment]
Followed the instruction in the link.  I don't see the error any more.  Thanks.
