### ISSUE TITLE
Make npm package for this

### ISSUE THREAD

**Issue by corysimmons** [joeblau/gitignore.io#173]
https://www.npmjs.com/package/gitignore doesn't let you have more than one ignored thing.

Make gitignore.io a global npm tool. Maybe call it `giio` (**g**it**i**gnore.**io**) or something.

```fish
$ giio node bower osx
```

would generate .gitignore in current dir.

The bash functions aren't sufficient since not everyone uses those. Plus, why have people pollute their shell config with stuff that could/should be `npm i -g giio`?

**Comment by corysimmons** [comment]
If you're too busy but would still like this feature, lemme know and i'll cook something up.

**Comment by joeblau** [comment]
gitignore.io will not be transitioning to an npm package in the foreseeable future for 3 reasons.

1.  Npm adds an extra dependency for absolutely no reason.  If i'm a Java platform developer and I don't ever need node/npm why should I have to install npm to install gitignore?  While this makes sense for the small subset of engineers who use node and npm, it doesn't make sense for this project.
2. Mainatianblitly - Having this tool run as node module breaks the [3rd core tenant of this website & service](https://github.com/joeblau/gitignore.io/wiki).  The update process for someone wanting to consume the latest gitignore.io templates goes from.
  - Me (maintainer) doing an update and deploying to web
  - developer running `gi file`
  to
  - Me (maintainer) doing an update and deploying to web
  - Me (maintainer) doing an update and deploying to npm
  - developer updating their node packages (if they even do that)
  - developer updating via node

 Having gitignore.io in npm increases the brittleness of ensuring that developers have the latest gitignore.io templates.
3. Shells are sufficient. Every machine comes with a shell installed by default; not every machine comes with npm.

If you want to create and maintain an npm package, by all means go for it.  I just don't see any immediate value in doing so as I'm trying to serve a wider community than then node community.

**Comment by corysimmons** [comment]
Sounds good. :+1:
