### ISSUE TITLE
Naked domain not redirecting properly

### ISSUE THREAD

**Issue by JoshWillik** [joeblau/gitignore.io#175]
The following redirects work correctly:

http://gitignore.io => https://www.gitignore.io
http://www.gitignore.io => https://www.gitignore.io
http://www.gitignore.io/api/node => https://www.gitignore.io/api/node

But when I try loading either of the following, I get a cloudflare error.
http://gitignore.io/api/node
https://gitignore.io/api/node

![screen shot 2016-02-04 at 12 23 41](https://cloud.githubusercontent.com/assets/2429492/12823466/2763f664-cb3a-11e5-9ce1-2621b3cbb2a4.png)

It's not a bug as much as it is annoying.

**Comment by joeblau** [comment]
I'll take a look into that... You should never be using http though anywhere on the internet if possible.

**Comment by joeblau** [comment]
Fixed. Thanks for catching this! :+1:

**Comment by JoshWillik** [comment]
That was fast. Thanks @joeblau!

**Comment by JoshWillik** [comment]
That was fast. Thanks @joeblau!

I realize http is bad. But I'm not in the habit of typing `https://` in front of URLs in my browser.

Though now that I think about it, I should probably just

```bash
curl https://www.gitignore.io/api/node > .gitignore
```

instead of copy paste from browser.

**Comment by joeblau** [comment]
You can also install gitingore in your shell: https://www.gitignore.io/docs

Then you can just type `gi node` and you won't have to worry about all of the http/https stuff from the command line.

**Comment by JoshWillik** [comment]
:+1: Cool, thanks!
