### ISSUE TITLE
Formula for image files

### ISSUE THREAD

**Issue by mcandre** [joeblau/gitignore.io#176]
`.jpg`, `.jpeg`, `.gif`, ...

**Comment by joeblau** [comment]
This is a pretty cool idea!  What do you think the template name should be?

**Comment by joeblau** [comment]
I've been looking at some sites to get a list of media templates.  here is one that seems to have a good amount of info.

http://www.youneeditall.com/web-design-and-development/file-extensions.html

**Comment by mcandre** [comment]
Name idea: "images"

**Comment by joeblau** [comment]
I like that, but maybe we should add a prefix or suffix to let people know that it's ignoring a specific class of files.
