### ISSUE TITLE
Remove heading, trailing blank lines

### ISSUE THREAD

**Issue by mcandre** [joeblau/gitignore.io#177]
Please remove the blank lines surrounding gitignore responses, so that gitignore plays better with command line tools.

**Comment by joeblau** [comment]
Which tools are you referring to in particular ?

**Comment by mcandre** [comment]
The clipboard. When I copy and paste into a gitignore with custom rules in addition to gitignore.io rules, I have to manually delete the extra lines.

**Comment by joeblau** [comment]
So there was issue https://github.com/joeblau/gitignore.io/pull/159 which someone filed before, but it seems like you and @corysimmons both would rather not have a leading newline.  While it does clean up the file, there is a negative consequence to someone who may already have an existing .gitignore file in their project directory which they are appending to.

Having a file with extra line spaces doesn't effect the template, but if you run `gi node >> .gitignore` and you already had a .gitignore file you created manually without a training blank line, the lack of having blank line would cause a problem.  How would you propose keeping the command simple for the basic user and protecting them against accidentally messing up an existing file while removing all extra white spaces?

**Comment by corysimmons** [comment]
Actually, I think this is a great opportunity for people to learn why newline at EOF on save is a thing.

gitignores are harmless and it seems it's inconveniencing your users (I can't live with superfluous newlines in my life) while letting newbs be ignorant of the importance of EOF newlines.

**Comment by joeblau** [comment]
> Actually, I think this is a great opportunity for people to learn why newline at EOF on save is a thing.

I see what you're saying, but the gaol of this project is not too educate people about EOF.  While I agree that having a nicely formatted file without leading and trailing spaces is nice, I'm still not convinced that it outweighs having a flat-out broken .gitignore file.

**Comment by corysimmons** [comment]
Eh I see where you're coming from. Oh well, will just continue to manually remove the newline every time because I'm OCD.

**Comment by joeblau** [comment]
Well if you're really OCD you can just use `gi node | sed '1d' >> .gitignore`

**Comment by corysimmons** [comment]
¯\\_(ツ)_/¯

**Comment by mcandre** [comment]
Newline at EOF is great, leading newline is awkward.

**Comment by joeblau** [comment]
Alright, I'm going to close this since https://github.com/joeblau/gitignore.io/pull/159 is still an issue that we can't work around yet.
