### ISSUE TITLE
Kobalt Build System Gitignore files

### ISSUE THREAD

**Issue by jaredsburrows** [joeblau/gitignore.io#184]
Basic `.gitignore` lines for https://github.com/cbeust/kobalt here:

```
### Kobalt ###
.kobalt
kobaltBuild/
```

@cbeust Anything else?

**Comment by cbeust** [comment]
LGTM.

**Comment by jaredsburrows** [comment]
I made a PR to the correct repo here: https://github.com/github/gitignore/pull/1893

**Comment by joeblau** [comment]
If you wanted to, you could have added it to the `/data/custom` directory until GitHub actually approves it.

**Comment by jaredsburrows** [comment]
@joeblau Thanks! Here is there PR: https://github.com/joeblau/gitignore.io/pull/185.

**Comment by joeblau** [comment]
https://www.gitignore.io/api/kobalt
