### ISSUE TITLE
installing vundle for windows (10)

### ISSUE THREAD

**Issue by ThatsVincent** [joeblau/gitignore.io#189]
hey,
Im trying to install vundle and everything works perfectly fine until I come to the point where I must paste something in curl.cmd . The problem is that I cannot find curl.cmd although I followed all the steps in the tutorial. 

link to the tutorial: https://github.com/VundleVim/Vundle.vim/wiki/Vundle-for-Windows

sorry for the stupid question
Kind regards
Vincent

**Comment by joeblau** [comment]
That doesn't seem to be related to this project :).  You may want to file this issue on Vundle's issue tracker: https://github.com/VundleVim/Vundle.vim/issues

**Comment by ThatsVincent** [comment]
thank you :) i will do it
