### ISSUE TITLE
Link to the repo on gitignore.io

### ISSUE THREAD

**Issue by rexim** [joeblau/gitignore.io#190]
Hi Joe!

First of all, thanks for such a great project! I use it constantly. :)

I remembered that gitignore.io is an Open Source project, but when I wanted to find the source code I didn't find the repo link on http://gitignore.io ! I actually had to go to google and experiment with queries just to get here!

May we have a link to this repo on http://gitignore.io ? I believe it will help to bring more contributors to the project. :)

Regards,
rexim

**Comment by joeblau** [comment]
Would a link that says "Source Code" be fine?

**Comment by rexim** [comment]
Yeah, it would be more than sufficient for me! Thanks! :)

**Comment by joeblau** [comment]
What about the [Fork Me Ribbon](https://github.com/blog/273-github-ribbons)

**Comment by rexim** [comment]
If they suite the design, they are good too. I think something from [GitHub Corners](http://tholman.com/github-corners/) with the #ff4f27 color, would look good. :)

**Comment by joeblau** [comment]
![screen shot 2016-03-29 at 10 30 35 am](https://cloud.githubusercontent.com/assets/1218847/14111633/6d35a974-f599-11e5-9e06-2fd924f9761b.png)

:+1:  or :-1:

**Comment by rexim** [comment]
Thank you very much sir!

**Comment by joeblau** [comment]
https://www.gitignore.io - site updated
