### ISSUE TITLE
packages folder

### ISSUE THREAD

**Issue by drauch** [joeblau/gitignore.io#194]
Hi!

When generating a Visual Studio gitignore file, the packages folder is excluded in the following way:

    # The packages folder can be ignored because of Package Restore
    **/packages/*

I propose to use:

    **/packages/

instead. I don't see a reason why to use the asterisk at the end, and it has a major downside: when executing `git stash`, the folder and all its content is deleted, which is not what you want to happen per default.

**Comment by joeblau** [comment]
Thanks for catching this.  There is one unfortunate challenge to this: The VisualStudio package is maintained by GitHub @ https://github.com/github/gitignore.  This site just references GitHub's master template list as a submodule so I don't modify anything that GitHub gives me, I only append.  I have a `.patch` file format that is helpful if you want to extend a template, but nothing yet that allows you to override a template or a subsection of a template.  The best course of action you can take right now is to suggest this change on GitHub's gitignore repository issue tracker.

**Comment by drauch** [comment]
Thanks for the pointer, now I understand. I'm going to create a pull request over at https://github.com/github/gitignore

Thanks for gitignore.io! All the best!

**Comment by joeblau** [comment]
:+1:
