### ISSUE TITLE
Issue when downloading

### ISSUE THREAD

**Issue by bluemonster122** [joeblau/gitignore.io#200]
when you download from the website, it downloads a file called "gitignore", instead of ".gitignore"

**Comment by joeblau** [comment]
That is correct. you have to modify the file after download to add the dot.  From what I've found you can't download dot files.

**Comment by joeblau** [comment]
If you want to get a direct download, you can use the [command line instructions](https://www.gitignore.io/docs) and type

```sh
gi :tempaltes: > .gitignore
```
