### ISSUE TITLE
Could use support for FontForge

### ISSUE THREAD

**Issue by csyde** [joeblau/gitignore.io#203]
I'm putting this up because I'm not quite sure how to contribute to someone else's GitHub project.

FontForge generates numerous save files in the pattern <filename>.sfd-## that usually require manual cleanup; I'm not sure if it's intentional or a very crude form of version control, but it creates a lot of clutter. I created a FontForge.gitignore file with the rule

\*.sfd-* 
*.sfd~

A FontForge-nobinaries.gitignore would add

*.ttf
*.ttc
*.otf
*.woff
*.pfb
*.pfa
*.pt3
*.suit

**Comment by joeblau** [comment]
Ah Fonts! would it make sense more to add everything into one file or keep them separate?

**Comment by csyde** [comment]
Hmmm... I imagine it depends on what the user looks for first? I know for my own font projects, I upload both the SFD files and binaries, so I wouldn't use the nobinaries entries. I'd say two separate files, maybe, if it's better not to overlap them. 

It would probably make sense to have something for Adobe Font Development Kit for OpenType too (compiles UFO files to binary), and perhaps Glyphs or FontLab, but I don't know anything about them so I wouldn't be able to help with that.

**Comment by joeblau** [comment]
I'm going to use the general font forge and add everything to that right now.  There is no real pattern of having a secondary subset right now.

**Comment by csyde** [comment]
Looks good!
