### ISSUE TITLE
Suggestion: Add CSharp as an alias of VisualStudio

### ISSUE THREAD

**Issue by sbrl** [joeblau/gitignore.io#208]
When I found the site at first, I wanted a C# gitignore file. The `VisualStudio` gitignore is exactly the thing I was looking for (it covers everything that you'd need it to), but I initially was looking under `CSharp` instead of `VisualStudio` (I use Monodevelop on linux). Adding an alias would help prevent confusion I think.

**Comment by joeblau** [comment]
I'm not a Visual Studio developer but is `CSharp` something that is commonly used amongst developers in that community?   The VisualStudio template is one of the original templates from GitHub's main repo and the template doesn't seem like it has anything that is C# specific, but we could definitely create the alias if it makes sense.

**Comment by sbrl** [comment]
I commit C# code to git repositories all the time - and prebuilt gitignore files are _so_ useful. I suggested `CSharp` because [Go Git Service](https://gogs.io/) has a `CSharp` template (which I assume is an alias of `VisualStudio`). I'm inclined to type the name of the language I'm writing in when searching for a gitignore file.

**Comment by joeblau** [comment]
Can you send me a copy of Gogs' template?

**Comment by sbrl** [comment]
Here you go:

```
# ---> C Sharp
# Build Folders (you can keep bin if you'd like, to store dlls and pdbs)
[Bb]in/
[Oo]bj/
# mstest test results
TestResults
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.
# User-specific files
*.suo
*.user
*.sln.docstates
# Build results
[Dd]ebug/
[Rr]elease/
x64/
*_i.c
*_p.c
*.ilk
*.meta
*.obj
*.pch
*.pdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.log
*.vspscc
*.vssscc
.builds
# Visual C++ cache files
ipch/
*.aps
*.ncb
*.opensdf
*.sdf
# Visual Studio profiler
*.psess
*.vsp
*.vspx
# Guidance Automation Toolkit
*.gpState
# ReSharper is a .NET coding add-in
_ReSharper*
# NCrunch
*.ncrunch*
.*crunch*.local.xml
# Installshield output folder
[Ee]xpress
# DocProject is a documentation generator add-in
DocProject/buildhelp/
DocProject/Help/*.HxT
DocProject/Help/*.HxC
DocProject/Help/*.hhc
DocProject/Help/*.hhk
DocProject/Help/*.hhp
DocProject/Help/Html2
DocProject/Help/html
# Click-Once directory
publish
# Publish Web Output
*.Publish.xml
# NuGet Packages Directory
packages
# Windows Azure Build Output
csx
*.build.csdef
# Windows Store app package directory
AppPackages/
# Others
[Bb]in
[Oo]bj
sql
TestResults
[Tt]est[Rr]esult*
*.Cache
ClientBin
[Ss]tyle[Cc]op.*
~$*
*.dbmdl
Generated_Code #added for RIA/Silverlight projects
# Backup & report files from converting an old project file to a newer
# Visual Studio version. Backup files are not needed, because we have git ;-)
_UpgradeReport_Files/
Backup*/
UpgradeLog*.XML

```

**Comment by sbrl** [comment]
@joeblau Thanks!
