### ISSUE TITLE
[LaTeX] Add *.lol to ignore list

### ISSUE THREAD

**Issue by Sharparam** [joeblau/gitignore.io#211]
The LaTeX [listings](http://ctan.org/pkg/listings) package will generate `*.lol` files when building (list of listings). These should be added to the ignore list for LaTeX.

(I'd make a PR myself but am unfamiliar with node projects.)

**Comment by joeblau** [comment]
Allow me to teach you how to fish -- No nodejs skills needed.

All of the data for this site is in the [./data](https://github.com/joeblau/gitignore.io/tree/master/data) directory.  This directory is broken down into 4 sections
  - classes - These are gitingore templates that cover a class of files like Images, Videos, Audio
  - custom - These are gitignore templates that aren't currently supported by GitHub
  - gitignore - This is a submodule to GitHub's master list of templates
  - patch - These patch files can be happened to any templates in the other directors to amend their configuration.  For example if you want to add a change to something on GitHub's master template list.

What you want to do is edit the `./data/custom/LaTeX.gitignore` and add your suggestion to the end of the file.  If you submit a PR with that, I can merge it.

**Comment by Sharparam** [comment]
Ah so it's that simple! I'll make a PR with it later today.
