### ISSUE TITLE
Invalid grunt-dependency, server.js does not load.

### ISSUE THREAD

**Issue by josteink** [joeblau/gitignore.io#213]
When trying to clone and build from git master, you get the following errors:

````bash
$ npm install
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-config-dir@0.3.2 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-dustjs@1.4.0 wants grunt@>=0.4.0

npm ERR! System Linux 3.13.0-83-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/jostein/build/gitignore.io
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jostein/build/gitignore.io/npm-debug.log
npm ERR! not ok code 0

$ nodejs server.js 
Server listening on http://localhost:8000
Unhandled rejection TypeError: Object java has no method 'startsWith'
    at /home/jostein/build/gitignore.io/models/datastore.js:115:39
    at Array.filter (native)
    at new DatastoreModel (/home/jostein/build/gitignore.io/models/datastore.js:114:10)
    at Object.<anonymous> (/home/jostein/build/gitignore.io/models/datastore.js:125:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jostein/build/gitignore.io/controllers/api/index.js:4:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Mon, 30 May 2016 08:42:22 GMT uncaughtException ENOENT, no such file or directory '/home/jostein/build/gitignore.io/models/../data/custom/AppCode.gitignore'
Error: ENOENT, no such file or directory '/home/jostein/build/gitignore.io/models/../data/custom/AppCode.gitignore'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at /home/jostein/build/gitignore.io/models/datastore.js:38:43
    at Object.oncomplete (fs.js:107:15)

````

Tested on both Fedora 23 and Ubuntu 14.04.

**Comment by joeblau** [comment]
It looks like you may need to update your node version.

I'm on node `v5.3.0` and nam `3.3.12`.  Try updating those and then see if it works.  If that fixes it, keep this task open and I'll update the instructions to ensure the correct node version.

**Comment by josteink** [comment]
I'm running whats coming with the package-manager's specifically:

On Fedora:

````
$ node --version
v0.10.42
````

On Ubuntu 14.04 LTS:

````
$ nodejs --version
v0.10.25
````

Is there any way to get a newer version of node, without bypassing the package-manager and breaking the system?

**Comment by joeblau** [comment]
The current version of node is: Current version: `v6.2.0`, your package manager should be update to date with the latest version.  What are you running to instal packages? You may have to update your package mangers data sources then update your packages.

https://nodejs.org/en/download/current/

**Comment by josteink** [comment]
I'm just running what's coming with the standard system package-managers and no additional repos.

I can try looking into adding custom repos for node later and see what version that gets me and if that fixes the problem.

But if so, like your say, not working with "standard" versions of node as provided through the system package manager probably needs to be documented better though.

**Comment by joeblau** [comment]
> I'm just running what's coming with the standard system package-managers and no additional repos.

In terms of security, you shouldn't really be running that. Gitignore.io is running with actively developed frameworks to take advantage of the latest patches and system architectural decisions. Node `v0.10.x` is in maintenance mode and will stop receiving updates in [October of this year](https://github.com/nodejs/LTS#lts_schedule).  Your version of Ubuntu is under LTS until 2019, but your version of node.js will stop receiving updates in 5 months. You may need to be more diligent than relying on your standard package manager defaults to provide you with updates.

![schedule](https://github.com/nodejs/LTS/raw/master/schedule.png)

> But if so, like your say, not working with "standard" versions of node as provided through the system package manager probably needs to be documented better though.

That is a great catch.  I'll update the documentation and package.json to let developers know that the project requires the **current version** of node (6.x) and not the maintenance or LTS version. 

You should go to https://nodejs.org/ and install the current version of nodejs then re-attempt to run gitignore.io locally.

**Comment by josteink** [comment]
Trying to use the package from nodesource, I get this:

````
jostein@thinkpad:~/build/gitignore.io% npm install
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global jshint@2.4.4 should be installed with -g
gitignoreio@1.0.0 /home/jostein/build/gitignore.io
...
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm WARN grunt-config-dir@0.3.2 requires a peer of grunt@~0.4.1 but none was installed.
jostein@thinkpad:~/build/gitignore.io% node server.js 
Server listening on http://localhost:8000
Application ready to serve requests.
Environment: development
Mon, 30 May 2016 12:45:31 GMT uncaughtException ENOENT: no such file or directory, open '/home/jostein/build/gitignore.io/models/../data/custom/AppCode.gitignore'
Error: ENOENT: no such file or directory, open '/home/jostein/build/gitignore.io/models/../data/custom/AppCode.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at /home/jostein/build/gitignore.io/models/datastore.js:38:43
    at FSReqWrap.oncomplete (fs.js:117:15)
jostein@thinkpad:~/build/gitignore.io% node --version
v6.2.0
jostein@thinkpad:~/build/gitignore.io% npm --version
3.8.9
````

Those are clearly different errors, but still errors. I can try with the direct binary download, but as far as I see it, gitignore.io does not seem to be running well on standard Linux distros using standard packages and repos.

I get what you say about developers, new frameworks and all that yadda yadda, but not running on a basic Linux system without adding lots of *untrusted and possibly insecure* third party repos is probably going to limit community engagement.

Obviously your project, so your choice, but still. Just thought I'd mention it.

**Comment by josteink** [comment]
Using latest tarball from the website doesn't yield any better results either:

````bash
jostein@thinkpad:~/Downloads% xz -d node-v6.2.0-linux-x64.tar.xz
jostein@thinkpad:~/Downloads% tar xf node-v6.2.0-linux-x64.tar 
jostein@thinkpad:~/Downloads% ls -l node-v6.2.0-linux-x64 /bin
-rwxr-xr-x 1 jostein jostein 27459658 May 17 21:40 node
lrwxrwxrwx 1 jostein jostein       38 May 17 21:40 npm -> ../lib/node_modules/npm/bin/npm-cli.js
jostein@thinkpad:~% cd ~/build/gitignore.io 
jostein@thinkpad:~/build/gitignore.io% ~/Downloads/node-v6.2.0-linux-x64/bin/npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm WARN grunt-config-dir@0.3.2 requires a peer of grunt@~0.4.1 but none was installed.
jostein@thinkpad:~/build/gitignore.io% ~/Downloads/node-v6.2.0-linux-x64/bin/node server.js 
Server listening on http://localhost:8000
Application ready to serve requests.
Environment: development
Mon, 30 May 2016 12:56:13 GMT uncaughtException ENOENT: no such file or directory, open '/home/jostein/build/gitignore.io/models/../data/custom/AppCode.gitignore'
Error: ENOENT: no such file or directory, open '/home/jostein/build/gitignore.io/models/../data/custom/AppCode.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at /home/jostein/build/gitignore.io/models/datastore.js:38:43
    at FSReqWrap.oncomplete (fs.js:117:15)
jostein@thinkpad:~/build/gitignore.io% 
````

It seems some of the dependencies are still not getting resolved on pretty standard desktop operating systems.

**Comment by joeblau** [comment]
Did you do a recursive clone of the repository?

**Comment by josteink** [comment]
Oops my bad. I just did a regular clone. If I do a `--recursive` clone, I actually get it up and running just fine. And that *is* documented. So much for complaining about documentation, eh?

**Comment by joeblau** [comment]
👍 - Cool glad it's working.  Once I update `package.json` and docs, I'll close this.
