### ISSUE TITLE
Intellij IDEA-Ignore misc.xml file ?

### ISSUE THREAD

**Issue by raj4dev** [joeblau/gitignore.io#215]
I think that .idea/misc.xml should be ignored, but it is not in the generated gitignore file.

**Comment by dotCipher** [comment]
👍  I agree.  It seems like *.iml / *.ipr are also not ignored

**Comment by joeblau** [comment]
@raj4dev This topic was discussed in a previous issue: #186 and there are a few things to consider.

1. The IntelliJ template is actually maintained by [GitHub's official repository](https://github.com/github/gitignore).  This proposal would be better off floated there.
2. If you read the [Intellij's official documentation](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839), also referenced in #186 it specifically states:

> All the files under .idea directory in the project root except the workspace.xml and tasks.xml files which store user specific settings

@dotCipher the documentation also says

> Share the project .ipr file and all the .iml module files, don't share the .iws file as it stores user specific settings

I can add them to the IntelliJ.patch file commented out. Each user would still be responsible for uncommented them on their own after creating a local `.gitignore` template.
