### ISSUE TITLE
Add instruction for fish config

### ISSUE THREAD

**Issue by SantoshSrinivas79** [joeblau/gitignore.io#216]
Thanks a ton for this!. (sorry ... i need to learn how to contribute properly)

FWIW. Could you add this installation tip for the fish config to the readme.

----

Create a file for the function using `vim ~/.config/fish/functions/gi.fish` and enter the below code

```sh


# Credit: https://geowarin.github.io/the-missing-fish-shell-tutorial.html
# Credit: https://github.com/joeblau/gitignore.io

function gi
  curl -L -s https://www.gitignore.io/api/$argv;
end

```
---

**Comment by joeblau** [comment]
Which operating system(s) does that command apply to?

**Comment by SantoshSrinivas79** [comment]
Oh. That is for Mac OSX (El Capitan) but I think it should work for Ubuntu too on the fish terminal.

**Comment by joeblau** [comment]
Why does is this line not added to `~/.config/fish/config.fish` ?

**Comment by joeblau** [comment]
Why is this added to ` ~/.config/fish/functions/gi.fish` and not to `~/.config/fish/config.fish`?

**Comment by joeblau** [comment]
I've added this command to the [wiki's advanced command line improvements](https://github.com/joeblau/gitignore.io/wiki/Advanced-Command-Line-Improvements).  If we can get this to a place where it's tested on multiple platforms then I'd be fine to merge it into the main README.md.
