### ISSUE TITLE
Add gogi for gitignore client

### ISSUE THREAD

**Issue by Gnouc** [joeblau/gitignore.io#224]
I write a simple gitignore client in Go https://github.com/Gnouc/gogi

It should be run on most OS, which support Go.

Would you mind adding `gogi` link to `README.md`?

**Comment by joeblau** [comment]
THIS IS AWESOME! Yeah, I'll add it in there tomorrow.  I need to re-work the `README.md` a little bit, but this is awesome!

Thanks for doing this.

**Comment by Gnouc** [comment]
@joeblau If you don't mind, I can make the PR :smile:

**Comment by joeblau** [comment]
Sure if you want that works.

**Comment by Gnouc** [comment]
@joeblau Sure, see https://github.com/joeblau/gitignore.io/pull/225

**Comment by joeblau** [comment]
It's live: https://www.gitignore.io/docs
