### ISSUE TITLE
License of generated .gitingore files?

### ISSUE THREAD

**Issue by CrazyPython** [joeblau/gitignore.io#229]
Do I need to add the license if I'm using the generated `.gitignore` files? And can I remove the notice at the top?

**Comment by joeblau** [comment]
> Do I need to add the license if I'm using the generated .gitignore files? 
No.

> can I remove the notice at the top?
Yep!

**Comment by CrazyPython** [comment]
@joeblau you should add a license to make it more clear for future users.

**Comment by joeblau** [comment]
Add the license where exactly?

**Comment by CrazyPython** [comment]
@joeblau on gitignore.io and in the repo

**Comment by joeblau** [comment]
The license has been at the bottom of the README.md[1] since the February of 2013.  I migrated it to a License file.

[1] - https://github.com/joeblau/gitignore.io/commit/98d860f1fb6f9c8550bb8d27d7b16d055eefc15f
