### ISSUE TITLE
rules for Eclipse IDE are not following good practices

### ISSUE THREAD

**Issue by mickaelistria** [joeblau/gitignore.io#230]
In the vast majprity of cases, it's recommended to keep and share the `.project`, `.settings` and other useful project metadata on SCM.

**Comment by mickaelistria** [comment]
Note that encouraging this kind of bad practice is a reason why people erroneously have some bad feelings with Eclipse IDE.

**Comment by joeblau** [comment]
Thanks for the feedback, the best way to get this updated is to file an issue with GitHub's main repository.  This project has a submodule reference to GitHub's.

https://github.com/github/gitignore

https://www.gitignore.io template generating algorithm only allows for amending GitHub's templates at the moment, not removing data.
