### ISSUE TITLE
F# .gitignore patterns should include build/ directory

### ISSUE THREAD

**Issue by rmunn** [joeblau/gitignore.io#234]
In the F# world, the most common default build directory is `build/`. Currently, neither the F# .gitignore pattern nor the Visual Studio .gitignore pattern include that directory, so when I create a new F# project via the Ionide IDE plugin (which uses the gitignore.io API to generate .gitignore files for new projects), the generated .gitignore file doesn't ignore build output produced by the default build script.

I was able to catch this because I paid attention to the output of `git add .` before blindly running `git commit` for my initial commit in my new project repository. But if I had been in a hurry I might have missed the fact that files in `build/` were being added to the Git index, and then I would have committed binaries into my repo.

There are two places where it would make sense to add `build/`. One would be in the F# `.gitignore` file, and the other one would be in the Visual Studio `.gitignore` file. The Visual Studio one makes more sense IMHO, since there's already `bld/` line in there, as well as several other build-related files. But that file is maintained by GitHub, and they might or might not accept the patch. (They want documentation with PRs, and there's no official documentation saying that F# build scripts usually build to a `build/` directory; it's just a *de facto* standard in the F# world, with no *de jure* documentation). So in order to patch this omission quickly, I think it makes sense to put `build/` into the F# `.gitignore` file, and leave the Visual Studio file alone until/if GitHub accepts a patch for it.

**Comment by bbodenmiller** [comment]
FYI there is concrete evidence at https://github.com/github/gitignore/pull/1814 as to why this should not be in the generic VisualStudio file.

**Comment by rmunn** [comment]
I'll submit a PR to move this to the F# `.gitignore` file. Note that it's less of a common default now than when I first wrote that, as ProjectScaffold defaults to `bin` like Visual Studio does, and the Ionide plugin now has an option to use ProjectScaffold for creating new projects. But Ionide still has a "New Project" option that creates a barebones build script that builds into the `build/` folder, so it's still worth keeping this line in the F# `.gitignore` for now.

Given https://gist.github.com/davidfowl/ed7564297c61fe9ab814, though, it's also worth considering taking `build/` (and `/build/`) out of the F# `.gitignore` completely. I'll make myself a note to revisit this in six months and see if the F# project landscape has changed.
