### ISSUE TITLE
Java rule blocks maven wrapper JAR files

### ISSUE THREAD

**Issue by gregturn** [joeblau/gitignore.io#237]
With a Java project, I get this:

```
### Java ###
*.class

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.ear

# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
hs_err_pid*
```

However, with Maven Wrapper, there is a JAR file at `.mvn/wrapper/maven-wrapper.jar` that needs to NOT be excluded.

**Comment by joeblau** [comment]
Can you submit this GitHub's repository: https://github.com/github/gitignore. You can reference this issue and when that one closes, I'll close this one.

**Comment by joeblau** [comment]
👍 When the parent is closed, I'll pull from GitHub and close this issue.

**Comment by thomaseizinger** [comment]
Just wanted to inform you that my PR (https://github.com/github/gitignore/pull/1768) which was duplicated by https://github.com/github/gitignore/pull/2117 has been merged and therefore the desired change is now in the master of https://github.com/github/gitignore.

**Comment by joeblau** [comment]
Thanks 👍
