### ISSUE TITLE
how to use the generated file ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [joeblau/gitignore.io#244]
[https://www.gitignore.io/api/jetbrains](https://www.gitignore.io/api/jetbrains)
**how to use the generated file ?**
@joeblau
@kennethklee 
@dashmug 

I just want to ignore **.idea folder** , in case of it were pushed to my github repo!

what should I do ?
I mean whether I need  just copy the content of t**he generated file** and add them to the origin .gitignore file,
or I have to create a new gitignore file ?
PS: (if I create a new file it will be override my origin .gitignore file of Python!)

**Comment by joeblau** [comment]
You can just append the template to your current .gitignore file *or* you can overwrite your existing template with the contents of the link above.

What you can also do is string multiple template together: https://www.gitignore.io/api/jetbrains%2Cpython

**Comment by xgqfrms-GitHub** [comment]
**Thanks for your reply!**
@joeblau

**Comment by xgqfrms-GitHub** [comment]
👍
