### ISSUE TITLE
Unity projects need .meta files!

### ISSUE THREAD

**Issue by SpAMCAN** [joeblau/gitignore.io#246]
.gitignores generated for Unity on here is set to ignore all .meta files; however, this causes issues with sprites and prefabs, causing them to forget their connections when moving between systems.

I was able to fix this by adding:
`# include meta files`
`!*.*.meta`

Cheers!

**Comment by joeblau** [comment]
Are you saying we should ignore them or keep them?

**Comment by SpAMCAN** [comment]
You should keep them. Currently you're ignoring them, which breaks links between prefabs, sprites, scripts and materials. I'm not sure if just getting rid of the `*.meta` line would catch everything, so I used the above lines at the end of my ignore file to allow meta files everywhere in the repo. Everything works since.

**Comment by joeblau** [comment]
The pattern in the file is `*.pidb.meta` so it's not ignoring all `*.meta` files.

[See the live template](https://www.gitignore.io/api/unity)

**Comment by SpAMCAN** [comment]
Double checking, it turns out this is a problem with doing both Unity and Visual Studio options in the same file. I guess VS also has a .meta file that it needs to skip over? 

Thanks anyway, apologies for flagging this as a problem with the Unity ignore template itself.

**Comment by joeblau** [comment]
You can report that to https://github.com/github/gitignore
