### ISSUE TITLE
Adding applications that use gitignore.io to README.md

### ISSUE THREAD

**Issue by hasit** [joeblau/gitignore.io#247]
Hello,

I developed a Visual Studio Code extension for gitignore.io called [gi](https://marketplace.visualstudio.com/items?itemName=rubbersheep.gi). I was wondering if there is a place for such applications in the README.md file since it is partially an SDK but enclosed into an extension for another tool.

I use gitignore.io a lot and would love to spread the joy of using it through this extension.

**Comment by joeblau** [comment]
We might have to make a new section on the README for extensions.  You can make one under the Other Clients section or I can add one this weekend.

**Comment by hasit** [comment]
Sent in a PR. Please let me know if you approve with the columns on the table or would like to change something.

Thanks.
