### ISSUE TITLE
Netbeans ignore assumes Netbeans to be at root

### ISSUE THREAD

**Issue by kaspercphbusiness** [joeblau/gitignore.io#249]
I am somewhat uncertain about this as I am relatively new to git.
The gitignore file produced by gitignore.io includes this pattern:
nbproject/private/
However, that pattern only matches nbproject/private if the netbean project is at the root of a git repository. That is not an assumption I always can make.
Hence I would think the right pattern to produce would be:
**/nbproject/private/
I tested out the various scenarios on the build-in git on macOS 10.12

**Comment by joeblau** [comment]
Thanks for the feedback.  Netbeans is actually managed by GitHub at this repository: https://github.com/github/gitignore/blob/master/Global/NetBeans.gitignore

You can file a ticket there.  Gitignore.io just uses `github/gitignore` as a submodule.

**Comment by kaspercphbusiness** [comment]
OK - I'll move it there. Thanks.
