### ISSUE TITLE
Using an API URL does not generate file sections in consistent order

### ISSUE THREAD

**Issue by bondolo** [joeblau/gitignore.io#253]
At one time

curl -o .gitignore https://www.gitignore.io/api/java,maven,netbeans,osx,linux,windows

generated a gitignore file containing sections in the listed order. It is currently generating the sections in a different indeterminate order. We have a development process which says to refresh the .gitignore every couple of months using the above command. The current diff which results is much larger than expected because of the section re-ordering. 

Please pick a method for ordering sections in the output file (perhaps use listed order) and use that same order consistently.

**Comment by joeblau** [comment]
Ah okay, I think this is due to the de-duplcating and dependency changes we recently added.  I'll take a look at those and maybe have to revert the dedupe changes.

**Comment by bondolo** [comment]
Thanks for looking in to it! A one time change would be fine as long as it is once again consistent going forward.

**Comment by joeblau** [comment]
Yeah it should be stable from now on :)
