### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/data/gitignore.io/models/../data/custom/AppCode.gitignore'

### ISSUE THREAD

**Issue by leehavin** [joeblau/gitignore.io#257]
I want to build to  local, but prompt an error!

**Error: ENOENT: no such file or directory, open '/data/gitignore.io/models/../data/custom/AppCode.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at /data/gitignore.io/models/datastore.js:38:43
    at FSReqWrap.oncomplete (fs.js:123:15)**

thanks!!

**Comment by joeblau** [comment]
Did you do a recursive git clone?

`git clone --recursive git@github.com:joeblau/gitignore.io.git`

If you don't do don't do that, you won't have the files that `AppCode.gitignore` symlinks to which is the `JetBrains.gitignore` template in GitHub's main repo.

**Comment by leehavin** [comment]
I downloaded the way through the http.
 --recursive    is right;
thanks!
