### ISSUE TITLE
Request: Add a footer comment in the generated output

### ISSUE THREAD

**Issue by gzm55** [joeblau/gitignore.io#264]
Hi, when writing scripts to automatic update the gitignore.io generating part of .gitignore file, I need a ending footer line to remove the correct lines. Now, we have to assume the gitignore.io part must be appended at the tail of .gitignore.

So how about the template of the generated files looking like:

```
# Created by https://www.gitignore.io/api/blabla
xxx
# End of https://www.gitignore.io/api/blabla 
```

**Comment by joeblau** [comment]
I'll take a look at this on vacation - it should be straight forward.
