### ISSUE TITLE
Search Bar doesn't work anymore (Google Chrome)

### ISSUE THREAD

**Issue by OnimeNoKyo** [joeblau/gitignore.io#306]
I can't  edit anymore in search bar
![image](https://cloud.githubusercontent.com/assets/11884364/22927996/7967f6d4-f2b4-11e6-89a3-0ea9c650efe6.png)

**Comment by joeblau** [comment]
When I've seen that happen, it usually seems to be a caching problem.  Can you go to the site in incognito?

**Comment by joeblau** [comment]
@OnimeNoKyo - can you double check that your cache is cleared when you try?

**Comment by OnimeNoKyo** [comment]
my bad ! it's working fine :+1:

**Comment by joeblau** [comment]
Awesome!
