### ISSUE TITLE
SonarLint plugin for JetBrains IDE

### ISSUE THREAD

**Issue by ozum** [joeblau/gitignore.io#317]
Hi,

I suggest `.idea/sonarlint` to be added JetBrains IDEs such as WebStorm etc. Sonar plugin for JetBrains IDE (SonarLint) generates issue cache files under that directory.

I couldn't see this under `sonar` and `webstorm` in `gitignore.io`.

Kind Regards,

**Comment by joeblau** [comment]
Are [Sonar](https://github.com/joeblau/gitignore.io/blob/master/data/custom/Sonar.gitignore) and SonarLint the same thing?

**Comment by ozum** [comment]
SonarLint (http://www.sonarlint.org/) is the plugin of Sonar for WebStorm and other JetBrains IDEs, Visual Studio and Eclipse. I'm a JetBrains customer, so I don't know what to put .gitignore for other IDEs.

For JetBrains it is `.idea/sonarlint`

**Comment by joeblau** [comment]
Maybe it makes sense to make it it's own file then?

**Comment by ozum** [comment]
In my opinion it is much better to include it into IDEs, because users don't have to search for every plugin for an IDE. Indeed other plugins are already included in WebStorm IDE .npmignore file such as:

```
# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Cursive Clojure plugin
.idea/replstate.xml

# Crashlytics plugin
```

To be consistent it should be added to IDE:
```
# Sonarlint plugin
.idea/sonarlint
```

**Comment by joeblau** [comment]
Okay, what I'm going to do is add it in the Intellij patch.  If you want that ignore in the canonical source, you're going to have to rely on submitting a PR to [GitHub](https://github.com/github/gitignore).

**Comment by ozum** [comment]
Does Intellij covers WebStorm?

**Comment by joeblau** [comment]
Yeah every IDE that IDEA Makes is symlinked to the same patch.

<img width="781" alt="screen shot 2017-03-24 at 7 29 39 am" src="https://cloud.githubusercontent.com/assets/1218847/24292420/aa5d6446-1063-11e7-84f3-a73bae6a8fbc.png">

**Comment by ozum** [comment]
That's great thank you.

**Comment by joeblau** [comment]
This will close automatically when I merge the pull request :)

**Comment by joeblau** [comment]
Tada! https://www.gitignore.io/api/webstorm

**Comment by ozum** [comment]
Thanks 👍
