### ISSUE TITLE
Option to support recursive ignore rules?

### ISSUE THREAD

**Issue by TjWallas** [joeblau/gitignore.io#335]
Is there an option on the web interface or an API query argument to enable recursive ignore rules?

For example, https://www.gitignore.io/api/lyx,vim,linux,latex only returns gitignore rules for the current directory and, I as a user would be interested in recursive ignore rules in the format: `**.bla` instead of `*.bla`

**Comment by joeblau** [comment]
At the moment there isn't.  If something should be ignore recursively, it should be specified in the template as a file that can potentially be anywhere in your git directory tree.

**Comment by joeblau** [comment]
If you believe that there should be an update to some of the ignore templates, please submit a pull request to: https://github.com/github/gitignore for templates that are hosted by GitHub.
