### ISSUE TITLE
IntelliJ plugin?

### ISSUE THREAD

**Issue by NickSamNam** [joeblau/gitignore.io#340]
Is an IntelliJ plugin in the works? Something like https://plugins.jetbrains.com/plugin/7495--ignore, but using your API.

**Comment by joeblau** [comment]
What does this mean?

**Comment by NickSamNam** [comment]
Sorry for being way to vague. I am wondering if an IntelliJ plugin is in the works. Something like https://plugins.jetbrains.com/plugin/7495--ignore, but using your API.

**Comment by joeblau** [comment]
I have no idea what the intellj plugin uses as it's source of data.  You might be better asking that question over there: https://github.com/hsz/idea-gitignore/issues

It seems like @hsz is the maintainer of that.

**Comment by joeblau** [comment]
I'm in the process of creating a more inclusive list of templates at https://github.com/dvcs/gitignore, but you'll need to talk to @hsz who maintains the intellij plugin if you want that project to update its source.
