### ISSUE TITLE
Search box not registering char after selecting something from Suggestion box

### ISSUE THREAD

**Issue by leslau** [joeblau/gitignore.io#343]
When you type something like "Java" and hit Enter, then next char you type didnt register on search box.

**Comment by joeblau** [comment]
Can you please tell me which browser, and operating system you are using?

**Comment by leslau** [comment]
ArchLinux 64bits + Chromium

It only happens when you select something from suggestion box and then backspace to delete it. After that it becomes buggy and starts ignoring first char

**Comment by joeblau** [comment]
Ah okay thanks for the details.  I'll take a look over the weekend.
