### ISSUE TITLE
Update the dvcs/gitignore submodule

### ISSUE THREAD

**Issue by lpalgarvio** [joeblau/gitignore.io#344]
Hello

Recent changes have been submitted to the [dvcs/gitignore](https://github.com/dvcs/gitignore) repository to add support for Drupal 7 and Drupal 8 templates, among others.

May you update the git submodule?

Thanks

**Comment by joeblau** [comment]
It was updated 6 days ago.

https://github.com/joeblau/gitignore.io/commit/54308538aff8d7dd4ff1fc8a1a6c42305033ebea
