### ISSUE TITLE
F# should be fsharp

### ISSUE THREAD

**Issue by jimmyp** [joeblau/gitignore.io#346]
`gi list` returns `f#` as a language you can generate patterns for.

However trying to use it results in an error:
```
08:12 $ gi f#

# Created by https://www.gitignore.io/api/f

#!! ERROR: f is undefined. Use list command to see defined gitignore types !!#

# End of https://www.gitignore.io/api/f
~/dev/scratch/fsharp-test/test
08:12 $
```

Perhaps `f#` should be changed to `fsharp`? C# is already under `csharp` Happy to submit a PR if you think this is a good idea

**Comment by joeblau** [comment]
Oh wow good catch!  Yeah it should be changed to fsharp.  If you want to submit the PR, please submit    it to: https://github.com/dvcs/gitignore.  If not, I can submit it as well.

**Comment by jimmyp** [comment]
ha, wrong repo

**Comment by joeblau** [comment]
Nah, It's my fault.  I'm move all of these projects under the DVCS banner.  It's just taking some time.
