### ISSUE TITLE
generateGitIgnore is not defined

### ISSUE THREAD

**Issue by Qix-** [joeblau/gitignore.io#351]
Getting an error in the console when trying to generate a new gitignore (hitting the button via the interface).

```
Uncaught ReferenceError: generateGitIgnore is not defined
    at HTMLButtonElement.onclick (www.gitignore.io/:63)
```

**Comment by joeblau** [comment]
Which browser and operating system are you on?

Can you also try loading the site in Incognito/Private Browsing?

**Comment by Qix-** [comment]
Chrome, MacOS. Does it on incog as well.

[Here's a recording](https://www.youtube.com/watch?v=xFuj5UOWYkY&feature=youtu.be). It was working fine about 24 hours ago.

**Comment by joeblau** [comment]
I'm seeing it too, but only on chrome right now.  Investigating what the issue is right now.

**Comment by joeblau** [comment]
Figured it out.  Just turned this off (This seems to be a Chrome feature only).

<img width="975" alt="screen shot 2017-04-30 at 6 14 55 pm" src="https://cloud.githubusercontent.com/assets/1218847/25568447/026f13e8-2dd1-11e7-87ea-bdaff76f103b.png">

Try it now.

**Comment by Qix-** [comment]
Fixed :) Thanks! <3

**Comment by joeblau** [comment]
Sweet.  Thanks for reporting!
