### ISSUE TITLE
Dropdown doesn't work as expected in IE

### ISSUE THREAD

**Issue by toubou91** [joeblau/gitignore.io#355]
Everybody is aware of the "We don't test for IE" concept  :bowtie:, but I thought I'd share:

![image](https://cloud.githubusercontent.com/assets/5684688/26240656/0885ea8a-3c82-11e7-86e7-8394f6192e7c.png)

**Comment by joeblau** [comment]
Which version of IE on which Version of Windows?

**Comment by toubou91** [comment]
It doesn't matter in the end, it's just IE :P

**Comment by joeblau** [comment]
Does it work in Edge?

**Comment by toubou91** [comment]
I don't know about Edge, I'm pretty sure, though, that I used an earlier version than Edge.

**Comment by joeblau** [comment]
Alright, Sorry about never getting to the bottom of this.  Hopefully the site or command line is still useful for you.

**Comment by toubou91** [comment]
No worries, I can understand how busy you are, it's the same here :-).

Cheers!
