### ISSUE TITLE
The entire .idea folder should *really* be ignored for IntelliJ IDEA, at least for Maven/Gradle users.

### ISSUE THREAD

**Issue by volkertb** [joeblau/gitignore.io#360]
I hate to start up this discussion again, but not having the .idea folder completely ignored is really an inconvenience for the vast majority of Java developers who use an IDE-independent build system such as Maven or Gradle.

I added the "intellij+iml" keyword when generating my .gitignore file on gitignore.io and it *still* wasn't enough, since Git wanted to add the following files:

* new file:   .idea/compiler.xml
* new file:   .idea/encodings.xml
* new file:   .idea/vcs.xml

I really don't need any of these files, since all the information contained therein are already defined in pom.xml and IntelliJ IDEA can always reconstruct this metadata from that POM when the metadata is missing. The POM makes all IDE metadata redundant and the same goes for build.gradle for Gradle projects.

Could you *please* create a profile called "intellij-maven" or "intellij-all-the-things" or whatever you'd like to call it and finally rid us of any and all IDE-specific cruft? Or perhaps even better, perhaps make gitignore.io smart enough that it will automatically ignore the entire .idea folder when it detects the combination of the flags "intellij" and either "maven" or "gradle"?

Thank you again in advance.

**Comment by joeblau** [comment]
Templates are managed on https://github.com/dvcs/gitignore.

You can create a symlink to the base intellij template called `intellij-maven.gitignore`, and then then add a your own `intellij-maven.patch`

> Could you please create a profile called "intellij-maven" or "intellij-all-the-things" or whatever you'd like to call it and finally rid us of any and all IDE-specific cruft? Or perhaps even better, perhaps make gitignore.io smart enough that it will automatically ignore the entire .idea folder when it detects the combination of the flags "intellij" and either "maven" or "gradle"?

If you don't have time to submit a PR on the other repo, I'll take a look at re-organizing the templates to be better.  I know there have been lots of complaints with GitHub's repo in how it handles different development environments, especially around this issue.  Now that gitignore.io's template library is not attached to GitHub's repo, we can finally move forward.

**Comment by orzechow** [comment]
As I stumbled into the same issue with PyCharm, I cleaned up the JetBrains templates, see https://github.com/dvcs/gitignore/pull/42

There will be an `JetBrains+iml` profile as well as `Intellij+iml`, `CLion+iml`, `PyCharm+iml`, etc. aliases.

Feel free to double check or edit the pull request.

**Comment by orzechow** [comment]
I have now added also `+all` variants to ignore the whole .idea folder: https://github.com/dvcs/gitignore/pull/43

**Comment by linkvt** [comment]
I think the issue mentioned by @volkertb is still not resolved. I understand it, that there should be a template for *all* files created by IntelliJ/Jetbrains IDEs, since everything is also contained in the build files.
He explicitely wants this ignore file to
> finally rid us of any and all IDE-specific cruft

The new `+all` templates don't ignore the files ignored by the `+iml` templates and are thus incomplete. They are rather `+idea` templates.

**Comment by joeblau** [comment]
Yeah, I'll try and take a deeper look tomorrow or on Sunday.  I'm also in the process of forking off from @github/gitignore templates so that should help since we don't have to be in sync with them anymore.  Trying to keep up with with they were doing was part of the problem since I used them as the master source and then just patched additions onto their templates.

**Comment by joeblau** [comment]
I'm going to close this, if you believe and update needs to be made to IntelliJ template, you can create a pull request on the [@dvcs/gitignore](https://github.com/dvcs/gitignore) repository.
