### ISSUE TITLE
Target Directory

### ISSUE THREAD

**Issue by igalbenardete** [joeblau/gitignore.io#361]
How come the target directory is not included for IntelliJ ?

**Comment by joeblau** [comment]
The original template was copied from https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore.  The templates on https://github.com/dvcs/gitignore are all based on GitHub's original list, but GitHub's list lacks flexibility that gitignore.io users are asking for.  I'm working update to address issues like this.

The main side effect of my proposed updates means that gitignore.io will fork from GitHub's.  Until recently I wasn't comfortable with doing that as GitHub has been pretty responsive with updating their templates.  The fork would me that when GitHub does it's template updates, gitignore.io won't automatically benefit from them.

**Comment by joeblau** [comment]
I'm going to close this task.  If you believe the IntelliJ template needs modification, you can submit a pull request on the [@dvcs/gitignore](https://github.com/dvcs/gitignore) repository.
