### ISSUE TITLE
SPM changes cause xcode project files to be ignored for "swift" target

### ISSUE THREAD

**Issue by rcritz** [joeblau/gitignore.io#366]
That's ok, maybe, if you're using SPM. However, there are a lot more swift projects out there being developed directly in xcode without SPM and this causes a vital, and unreconstructable portion of the project to be excluded from source control.

**Comment by joeblau** [comment]
Could you please elaborate more.  Which versions of Swift Package Manager and Xcode?

**Comment by rcritz** [comment]
The versions of SPM and Xcode don't matter, actually. The problem is that someone added "*.xcodeproj" when they added the SPM section to the Swift .gitignore file.  That's great if you're using SPM and letting it generate your project file. It's a disaster waiting to happen if you don't use SPM (the majority of Swift projects) and, in fact, start with an Xcode project. 

Carthage and CocoaPods sections were moved out into independent files. I'd recommend the same for SPM since the majority of Swift programs don't use it.

**Comment by joeblau** [comment]
Oh you mean in the template! Hah I was confused at first.  So what you're referring to is this.

https://github.com/dvcs/gitignore/blob/master/templates/SwiftPackageManager.gitignore#L4

**Comment by rcritz** [comment]
Yes.  If I do "git ignore swift" (I have it aliased to pull from the site),
it ends with:

### Swift.SwiftPackageManager Stack ###
Packages
.build
xcuserdata
*.xcodeproj

Earlier in the output you find:

# CocoaPods - Refactored to standalone file

# Carthage - Refactored to standalone file

Which strikes me as a good thing to do with SPM as well. That way, you can
do something like "git ignore swift,macos,spm >.gitignore" if and only if
you're using SPM and not have it exclude the Xcode project file for all
swift projects.
