### ISSUE TITLE
Swift template ignore *.xcodeproj

### ISSUE THREAD

**Issue by SuEric** [joeblau/gitignore.io#367]
# Swift template ignore *.xcodeproj

Yesterday I created a new xcode project and I realized my mate had problems with the project after pulling since template generated a *.gitignore* file with *.xcodeproj*

Is this behavior expected?? Why ignore the project file; I think this is needed for opening an Xcode Project.

**Comment by joeblau** [comment]
Ah that's due to the SwiftPM stack.  I'll remove that.
