### ISSUE TITLE
Simplify update of gitignore

### ISSUE THREAD

**Issue by Djabx** [joeblau/gitignore.io#371]
I create a file with this conf:

* c++
* java

But then I realise I forget some things...
It would be great if I could take the url at the top of the gitignore file (: https://www.gitignore.io/api/c++,java ) and just add some other tings like this: https://www.gitignore.io/api/qt,c++,java,code,linux .

**Comment by joeblau** [comment]
Hm.. this *is* interesting.  You can do that, but you'd have to re-download the file again.  The other thing you could do from the command line is run:

```sh
gi qt,code,linux >> .gitignore
```
which would append to your file, but it's not the same as having a brand new file with all of the templates you want to ignore.  This is a really good idea, I just need to think about how to make it painless :).

**Comment by Djabx** [comment]
@joeblau thank you !
I'm not a web developer myself, but I just take a look to your code.
Maybe, in `app.js` (line 1) we can do something like this:

     $(".ignore-search").select2({
        sorter(results) {
            const query = $('.select2-search__field').val().toLowerCase();
            return results.sort((a, b) => a.text.toLowerCase().indexOf(query) -
                b.text.toLowerCase().indexOf(query));
        },
        processResults: function (data) {
            return {
                results: [].concat.apply([],
                    data.map(x => !x.contains(',') ? x : x.split(',')))
            };
        },
        minimumInputLength: 1,
        theme: "bootstrap",
        multiple: true,
        data
    });
    });

The idea is, if the input have some coma, we split. Sound enough ?

**Comment by joeblau** [comment]
I just tried to test your pull request and it doesn't seem to work or I don't understand how it works.  Could you explain a little more how the field is pre-populated?

**Comment by Djabx** [comment]
No, I'm just dumb and read too quickly the exemple:
https://select2.github.io/examples.html#data-ajax
I thought that the `processresult` was for the user input, but it's for the request...

I think the correction must take place in `select2` component.

**Comment by joeblau** [comment]
Ah okay, Yeah if you can get it working in your pull request, I can merge it.  I've had some issues trying to make select2 do what I want.

**Comment by joeblau** [comment]
Fixed by #429. There is now a url in the template that takes you to a like where you can update the existing templates.
