### ISSUE TITLE
[Terraform] .tfvars should not be excluded

### ISSUE THREAD

**Issue by rochdev** [joeblau/gitignore.io#375]
This was introduced with https://github.com/joeblau/gitignore.io/pull/192.

Terraform best practices is to store whatever you can in .tfvars, and leave out anything sensitive or that you want to input interactively.

The default should not be to exclude .tfvars. If needed it should be done by project.

References:
https://www.terraform.io/intro/getting-started/variables.html
https://github.com/hashicorp/best-practices/blob/master/terraform/providers/google/us_central1_prod/terraform.tfvars

**Comment by joeblau** [comment]
You can submit a pull request to https://github.com/dvcs/gitignore to update the template.
