### ISSUE TITLE
运行起来后，不能create创建

### ISSUE THREAD

**Issue by MrLichangming** [joeblau/gitignore.io#377]
（1）、git clone https://github.com/joeblau/gitignore.io.git
（2）、vapor build
（3）、vapor run  后，显示：
   You might not have done a recursive clone to update your submodules:
   `git submodule update --init --recursive`
  No command supplied, defaulting to serve...
  No preparations.
  Server 'default' starting at 0.0.0.0:8080
（4）、访问页面：
在文本框内输入python，no  create；

这是怎么回事呢？

**Comment by joeblau** [comment]
There seems to be a bug if you follow these steps:

1. Enter Python
2. Press Create
3. Press back on the browser
4. Press Create again - (At this step nothing happens)

I'll figure out what's going on with this.

**Comment by cafeimao** [comment]
I follow the tutorial on github, the local environment, install the swift 4.0 framework, vapor 3.0 version;
OS： Ubuntu16.04
(1)、Git clone -- recursive git@github.com: joeblau/gitignore. IO. 
（2）、Git showed no permission to connect, I try to download zip code file, and then,
（3）、 cd  gitignore. io/  
（4）、execution 
vapor builds 
vapor run, 
（5）、access to the web site, shows the ignore. io  page, just can't create ignore files;

**Comment by joeblau** [comment]
Per the `Package.swift` file, the app works with vapor 1.5, not vapor 3.  I'm not sure if vapor 3.0 supports localization but I need that for some of my international users.

https://github.com/joeblau/gitignore.io/blob/master/Package.swift

**Comment by cafeimao** [comment]
How is vapor1.5 installed

**Comment by joeblau** [comment]
`swift package fetch`

**Comment by cafeimao** [comment]
Hello, I have cloned gitignore from github to local, and I entered the gitignore.io folder and implemented the vapor build. Then I encountered these mistakes. What is the problem, please?
Vapor build
No. Build folder, fetch may take a while...
Fetching Dependencies [•]
Error: backgroundExecute(code: 1, Error: "warning: \'fetch\' command is deprecated;Use \'resolve\' instead\nerror: invalidAccess\n ', output: '

**Comment by joeblau** [comment]
I've updated to vapor 3, can you try the clone build and run steps again please?

**Comment by joeblau** [comment]
Please re-open this ticket if vapor 3 doesn't work.

**Comment by MrLichangming** [comment]
thank you !  I have solved it
