### ISSUE TITLE
Do not ignore vendor/ for Go

### ISSUE THREAD

**Issue by ahmetb** [joeblau/gitignore.io#379]
`vendor/` definitely should not be in gitignore. That's a major problem.
See https://github.com/github/gitignore/blob/master/Go.gitignore.

**Comment by joeblau** [comment]
Please file a pull request on the template repo: https://github.com/dvcs/gitignore

**Comment by ahmetb** [comment]
Consider creating an ISSUE_TEMPLATE that describes this. It's not clear where the template repo is on the website (or in this repo).
