### ISSUE TITLE
Don't let users ignore global stuff

### ISSUE THREAD

**Issue by corysimmons** [joeblau/gitignore.io#38]
Nothing in [this folder](https://github.com/github/gitignore/tree/master/Global) should be available. Instead, when someone goes to add `OSX` at least throw a warning and redirect them [here](https://help.github.com/articles/ignoring-files#global-gitignore).

It's bad practice.

**Comment by joeblau** [comment]
I added documentation on the help page to help users create a `~/.gitignore_global` directory.
