### ISSUE TITLE
Ignore components in VisualStudio

### ISSUE THREAD

**Issue by jerone** [joeblau/gitignore.io#381]
I would like to propose to ignore the whole `components` folder and it's contents for Visual Studio. 

The components folder is created when installing [Components](https://components.xamarin.com/) from Xamarin module inside Visual Studio. Components are just like NuGet, they [shouldn't be included in source control](https://forums.xamarin.com/discussion/15162/what-parts-of-a-component-should-be-checked-into-source-control), and are automatically restored when opening the project for the first time.

**Comment by joeblau** [comment]
Can you please submit a pull request on the [@dvcs/gitignore](https://github.com/dvcs/gitignore) repository.
