### ISSUE TITLE
vapor build : Error

### ISSUE THREAD

**Issue by MrLichangming** [joeblau/gitignore.io#384]
vapor build  error:
   root@ignore-virtual-machine:/gitignore.io#   vapor build
Building Project [Failed]

Command:
build --enable-prefetching

Error (1):
<unknown>:0: error: unable to attach DB: error: accessing build database "/gitignore.io/.build/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
error: terminated(1): /usr/bin/swift-build-tool -f /gitignore.io/.build/debug.yaml main

Output:

Toolchain:
/usr/bin/swift

Help:
Join our Slack where hundreds of contributors
are waiting to help: http://vapor.team

**Comment by joeblau** [comment]
This app isn't updated to the latest version of Vapor.  If you use the docker deployment this works a lot easier.

**Comment by joeblau** [comment]
I've migrated to the latest version of vapor.  If you're still having build problems, please re-open this issue.
