### ISSUE TITLE
Vim gitignore conflicts with .ssh

### ISSUE THREAD

**Issue by jody-frankowski** [joeblau/gitignore.io#386]
Vim gitignore template excludes `.ssh` files/directories.
[This](https://github.com/dvcs/gitignore/blob/a3383e90b6603f7f209fa68c9affb0d0316cf8f7/templates/Vim.gitignore#L4) is the problematic rule.

### Expected Behavior:

The template only excludes vim related things.

### Actual Behavior:

The template excludes things not related with vim.

### Reproduction Steps:

```sh
mkdir .ssh
touch .ssh/config
git check-ignore .ssh/config -v
/home/me/.gitignore:269:[._]s[a-v][a-z] .ssh/config
```

**Comment by joeblau** [comment]
Template changes should be submitted as a pull request on the template repo.

https://github.com/dvcs/gitignore

**Comment by jody-frankowski** [comment]
Ok, I see. However I don't know what the original author intended, so I don't know how I could restrict the regex without interfering with the original intention.

**Comment by joeblau** [comment]
That's fine.  Submit a pull request, I'll approve it and *trust me*, when someone has a contradicting view, they'll submit a pull request and then we'll find out.

I created my own [.gitignore](https://github.com/dvcs/gitignore) template repo so I don't have to go through GitHubs formal process of trying to figure out what's in the documentation.  We'll let the power of open source communication sort it out.
