### ISSUE TITLE
SAS.gitignore shoul have leading * for each pattern

### ISSUE THREAD

**Issue by ShuguangSun** [joeblau/gitignore.io#388]
# Issue Template

In SAS.gitignore, it just provide pattern like:
.sas7baud
which will not match filename.sas7baud, and usually SAS will generate *.sas7baud instead of .sas7baud.

### Expected Behavior:

*.sas7baud
*.sas7bdat
*.sas7bvew
*.sas7bndx
*.sas7bcat
*.sas7bacs
*.sas7bfdb
*.sas7bmdb
*.sas7bdmd
*.sas7bitm
*.sas7butl
*.sas7bput
*.sas7bbak

**Comment by joeblau** [comment]
Template changes should be submitted as a pull request on the template repo.

https://github.com/dvcs/gitignore
