### ISSUE TITLE
gi.cmd command change for x64 Git version

### ISSUE THREAD

**Issue by NJT145** [joeblau/gitignore.io#390]
if you use 64 version of Git, change "mingw" with "mingw64" in gi.cmd code to make it work.

**Comment by joeblau** [comment]
I'm not sure I understand what's going on.  What is mingw?

**Comment by NJT145** [comment]
for cmd script gi.cmd , the code on website is:
#################
@rem Do not use "echo off" to not affect any child calls.
@setlocal

@rem Get the abolute path to the parent directory, which is assumed to be the
@rem Git installation root.
@for /F "delims=" %%I in ("%~dp0..") do @set git_install_root=%%~fI
@set PATH=%git_install_root%\bin;%git_install_root%\mingw\bin;%PATH%

@if not exist "%HOME%" @set HOME=%HOMEDRIVE%%HOMEPATH%
@if not exist "%HOME%" @set HOME=%USERPROFILE%

@curl.exe -L -s https://www.gitignore.io/api/%*
###########################
however, if your git is x64 version instead of x32, %git_install_root%\mingw\bin does not exist, but %git_install_root%\mingw64\bin exist and this is where curl.exe is. so, for git at x64 pc, the code should be:
#################
@rem Do not use "echo off" to not affect any child calls.
@setlocal

@rem Get the abolute path to the parent directory, which is assumed to be the
@rem Git installation root.
@for /F "delims=" %%I in ("%~dp0..") do @set git_install_root=%%~fI
@set PATH=%git_install_root%\bin;%git_install_root%\mingw64\bin;%PATH%

@if not exist "%HOME%" @set HOME=%HOMEDRIVE%%HOMEPATH%
@if not exist "%HOME%" @set HOME=%USERPROFILE%

@curl.exe -L -s https://www.gitignore.io/api/%*
###########################
that's the only point i want to clearify to help others.

**Comment by joeblau** [comment]
Ah thanks! Sorry I forgot that section was even in the instructions.  Do you think it would be better to have two separate sections: one for 32 and one for 64 bit?

**Comment by NJT145** [comment]
or, you can change your code to check if mingw path exist. You can use this:
############################
@rem Do not use "echo off" to not affect any child calls.
@setlocal

@rem Get the abolute path to the parent directory, which is assumed to be the
@rem Git installation root.
@for /F "delims=" %%I in ("%~dp0..") do @set git_install_root=%%~fI
@for /F "delims=" %%I in ("%~dp0..") do @set git_mingw_root=%%~fI\mingw
@if not exist "%git_mingw_root%" @set git_mingw_root=%git_install_root%\mingw64
@set PATH=%git_install_root%\bin;%git_mingw_root%\bin;%PATH%

@if not exist "%HOME%" @set HOME=%HOMEDRIVE%%HOMEPATH%
@if not exist "%HOME%" @set HOME=%USERPROFILE%

@curl.exe -L -s https://www.gitignore.io/api/%*
######################

**Comment by joeblau** [comment]
Do you want to submit a pull request so you get the credit or do you want me to just make the change?

**Comment by NJT145** [comment]
you can do the change.

**Comment by NJT145** [comment]
wait, i change my choice, i prefere to do a pull request

**Comment by NJT145** [comment]
but i dont know how to do it :(

**Comment by NJT145** [comment]
okay. i learned it. i will try

**Comment by NJT145** [comment]
okay. i did a pull request. thanks.

**Comment by joeblau** [comment]
Thanks! You got it!
