### ISSUE TITLE
The file cannot be created in the Web UI

### ISSUE THREAD

**Issue by MrLichangming** [joeblau/gitignore.io#395]
### Development Environment:

- [ ] Machine (Local, Container, Virtual):
Container
- [ ] Operating System (Name/Version):
Centos7
- [ ] Web Browser (Name/Version):
 chrome
- [ ] Vapor Version:
Vapor Toolbox: 1.0.9
- [ ] Swift Version:
Swift version 3.1 (swift-3.1-RELEASE)
when Start the container according to docker-compose. Yml. ,can't create ignore file
###Error info
app_1  | Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 11 ("Resource temporarily unavailable") [readFailed]))

**Comment by joeblau** [comment]
Hm... I'm not 100% sure what is needed to start a docker container for this app.  @lucasvalenteds can you help this guy out please since you submitted the docker PR support?

**Comment by lucasvalenteds** [comment]
@MrLichangming What the browser shows when you tell what files to ignore and click the `Create` button? Does the error you've mention happens when you run `docker-compose up -d` or `docker-compose logs`?

There is [an issue](https://github.com/vapor/vapor/issues/689) in the vapor repository that describes this behavior.

**Comment by lucasvalenteds** [comment]
@joeblau The Docker support was added to avoid the process of installing Swift and Vapor in my system just to host the gitignore.io app and nothing else.

There are instructions to run the container in the README file, right below the instructions commands. You just have to install both Docker and Docker Compose and type `docker-compose up -d` inside the cloned repository folder and it's done. Do you think the instructions should be rewritten using a more detailed approach?

**Comment by joeblau** [comment]
Docker instructions are great! Thanks for adding them.  Super helpful for debugging as well.
