### ISSUE TITLE
Extend LaTeX template

### ISSUE THREAD

**Issue by jnboehm** [joeblau/gitignore.io#397]
There are a couple patterns that I miss.

```
*.figlist
*.makefile
*-figure[0-9]*.pdf
*-figure[0-9]*.dep
*-figure[0-9]*.md5
*.glstex
```

1. `*.figlist` and `*.makefile`: they are produced by using `\tikzexternalize[list and make]`
2. `*-figure[0-9].*`: these are generated by tikzexternalize as well.
3. `*.glstex`: is produced by the `glossaries-extra` package, when using a .bib-file to generate the glossary.

If it is necessary to submit a pull request, please let me know.  Otherwise just commit the list and close the issue.

Thank you!

**Comment by joeblau** [comment]
Can you please submit these suggestions to https://github.com/dvcs/gitignore
