### ISSUE TITLE
Update the templates

### ISSUE THREAD

**Issue by olicht** [joeblau/gitignore.io#398]
Just need to update the templates from [@dvcs/gitignore](https://github.com/dvcs/gitignore). 

Maybe create a task to auto-import the changes...

**Comment by joeblau** [comment]
Every merged pull request automatically gets pushed to https://staging.gitignore.io.  It usually just don't ship it to https://gitignore.io for a few days to make sure nothing is crashing.  I could change the deployment process to just auto ship template changes although I have seen instances where template files contain some crazy unicode characters that crash the template parser.

Just pushed latest staging to prod. 👍
