### ISSUE TITLE
SBT Scala and Intellij combination throws error

### ISSUE THREAD

**Issue by Nithanaroy** [joeblau/gitignore.io#405]
# Issue Template

## Frequently Asked Questions

**Q:** How do I submit a new <code>.gitignore</code> templates?  
**A:** Please submit all new templates to [@dvcs/gitignore](https://github.com/dvcs/gitignore).

**Q:** How do I suggest modifications to existing `.gitignore` templates?  
**A:** Modifictions should come in the form of pull requests at [@dvcs/gitignore](https://github.com/dvcs/gitignore).

**Q:** Why don't Gitignore.io's templates don't look exactly like the templates on [@github/gitignore](https://github.com/github/gitignore)?  
**A:** Gitignore.io tried to maintain parity with [@github/gitignore](https://github.com/github/gitignore), but GitHub's template list doesn't include many languages, operating systems, and IDE's that developers use.  Gitignore.io's template list has over 100 more templatess than GitHub's.

**Q:** Why is my local site empty?  
**A:** When the repository is cloned, the `--recursive` flag is necessary.  gitignore.io uses @dvcs/gitignore as it's data source.  If  the repo isn't cloned recursively, templates will be missing.

## Issue

Error thrown for the combination: `sbt intellij scala`

### Development Environment:

- [ ] Machine (Local, Container, Virtual):
- [ ] Operating System (Name/Version):
- [ ] Web Browser (Name/Version):
- [ ] Vapor Version:
- [ ] Swift Version:

### Expected Behavior:
Generate the combined gitignore file

### Actual Behavior:
```

# Created by https://www.gitignore.io/api/sbt%2Cscala%2Cintellij

#!! ERROR: sbt%2cscala%2cintellij is undefined. Use list command to see defined gitignore types !!#


# End of https://www.gitignore.io/api/sbt%2Cscala%2Cintellij
```

### Reproduction Steps:
Add SBT, Intellij and Scala on the gitignore.io home page and press generate button

**Comment by joeblau** [comment]
Seems like there is a problem sending a url encoded string.  With actual commas, this works: https://www.gitignore.io/api/sbt,scala,intellij

**Comment by joeblau** [comment]
This is fixed now, go back to https://www.gitingore.io and try again please.
