### ISSUE TITLE
kotlinc.xml should add it in gitignore

### ISSUE THREAD

**Issue by diegohdez90** [joeblau/gitignore.io#408]
Hi gitignore community, I've updated my Android Studio to 27.0.3 (latest version)
When I updated my repoxitory I see over `.idea` directory a new file named `kotlinc.xml`

My doubt is if I have to add this file in `.gitignore` or this file should be to commit?

**Comment by joeblau** [comment]
Can you add this template to https://github.com/dvcs/gitignore
