### ISSUE TITLE
Support for Ballerina Programming Language

### ISSUE THREAD

**Issue by abdennour** [joeblau/gitignore.io#414]
## Feature : Support for Ballerina Programming Language

[Ballerina programming platform](https://ballerina.io/) generates files and directories that should not be tracked via  GIT.

According to my first examples/helloworlds of Ballerina, I can suggest ignoring the following : 

```
*.log
*.balx
kubernetes/

```

**Comment by joeblau** [comment]
Can you submit this template to https://github.com/dvcs/gitignore so you get the credit.

**Comment by abdennour** [comment]
Thank you @joeblau . I did it: https://github.com/dvcs/gitignore/pull/124

**Comment by joeblau** [comment]
Cool and thanks — I'll merge it.
