### ISSUE TITLE
Add one-liner CLI install for Windows

### ISSUE THREAD

**Issue by NathanUrwin** [joeblau/gitignore.io#419]
### Development Environment:

- [x] Operating System (Name/Version): Windows 10
- [x] Machine (Local, Container, Virtual): Local
- [ ] Web Browser (Name/Version):
- [ ] Vapor Version:
- [ ] Swift Version:

### Expected Behavior:

`gig` command should persist between PowerShell sessions.

### Actual Behavior:

```powershell
gig : The term 'gig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ gig
+ ~~~
    + CategoryInfo          : ObjectNotFound: (gig:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Reproduction Steps:

Follow the [Command Line Docs for Windows](https://www.gitignore.io/docs#-install-command-line-windows), close and re-open PowerShell.

### Recommended Fix:

Update the docs to include adding the PowerShell functions to the Windows user `$profile`. See [source](https://social.technet.microsoft.com/Forums/windowsserver/en-US/a1350c44-83e6-4d54-9e6a-eded642e89c4/functions-always-in-my-profile?forum=winserverpowershell).

**Comment by joeblau** [comment]
Would you be able to update the docs to reflect exactly what they should say?  I haven't used windows since 2008 and I want to make sure the documentation is accurate.

**Comment by NathanUrwin** [comment]
I'm actually in the same boat as you now 😅 

I haven't been on Windows pretty much since I made this issue... if I have the urge to buy a gaming PC this will be the first thing I do 👍

**Comment by joeblau** [comment]
Someone who lives and dies on Windows — if you have a solution, please submit a PR 👍
