### ISSUE TITLE
Add url params to gitignore.io

### ISSUE THREAD

**Issue by jswright61** [joeblau/gitignore.io#421]
It would be great to add url params to the website such that keywords can be automatically populated on first load. Rather than linking directly to the api, a link to https://www.gitignore.io?keywords=osx,sublimetext would open the main screen with the search box pre-populated with the included search terms. Unrecognized terms would be ignored. It could also be implemented without the ? and keyword=, such as https://www.gitignore.io/osx,sublimetext - I'll leave the implementation details to you.

**Comment by joeblau** [comment]
Yeah I've attempted to do that before, but I had a problem injecting that into Select2 cleanly.  Definitely keep this open because it's something I want to look at.
