### ISSUE TITLE
readme page is broken

### ISSUE THREAD

**Issue by Foadsf** [joeblau/gitignore.io#422]
The [README.md](https://www.gitignore.io/README.md) page is broken. This is what I see:

![untitled](https://user-images.githubusercontent.com/12762442/44792538-64dd2180-aba4-11e8-8bc5-0cd10dcd7c9c.png)

**Comment by joeblau** [comment]
Whoa! what url are you going to?

**Comment by Foadsf** [comment]
@joeblau this https://www.gitignore.io/README.md

**Comment by joeblau** [comment]
Ah yeah, that's going to render raw markdown that's not processed.  You should be going to https://www.gitignore.io/docs

**Comment by Foadsf** [comment]
@joeblau that link was given to me by Google. So if people are going to end up there maybe you should fix it.

**Comment by joeblau** [comment]
Ah okay, I'll have to fix that.  Thanks for your help in identifying that.
