### ISSUE TITLE
Android Studio 3.2 new folder added, /.idea/codeStyles

### ISSUE THREAD

**Issue by iArsalanshah** [joeblau/gitignore.io#428]
# Issue Template

## Frequently Asked Questions

**Q:** How do I submit a new <code>.gitignore</code> templates?  
**A:** Please submit all new templates to [@dvcs/gitignore](https://github.com/dvcs/gitignore).

**Q:** How do I suggest modifications to existing `.gitignore` templates?  
**A:** Modifictions should come in the form of pull requests at [@dvcs/gitignore](https://github.com/dvcs/gitignore).

**Q:** Why don't Gitignore.io's templates don't look exactly like the templates on [@github/gitignore](https://github.com/github/gitignore)?  
**A:** Gitignore.io tried to maintain parity with [@github/gitignore](https://github.com/github/gitignore), but GitHub's template list doesn't include many languages, operating systems, and IDE's that developers use.  Gitignore.io's template list has over 100 more templatess than GitHub's.

**Q:** Why is my local site empty?  
**A:** When the repository is cloned, the `--recursive` flag is necessary.  gitignore.io uses @dvcs/gitignore as it's data source.  If  the repo isn't cloned recursively, templates will be missing.

### Development Environment:

- [ ] Machine (Local, Container, Virtual):
- [ ] Operating System (Name/Version):
- [ ] Web Browser (Name/Version):
- [ ] Vapor Version:
- [ ] Swift Version:

**Comment by joeblau** [comment]
Please read the FAQ. Templates are submitted at https://github.com/dvcs/gitignore
