### ISSUE TITLE
Readme coverage badge has gray "unknown" status

### ISSUE THREAD

**Issue by matkoniecz** [joeblau/gitignore.io#431]
it is visible directly above https://github.com/joeblau/gitignore.io#gitignore-template-source

**Comment by joeblau** [comment]
Yeah, test coverage isn't setup through code climate and I'm probably not going to set it up for this repo.  I've got a new monorepo that I'm building and that one will have the appropriate configs for everything.

**Comment by joeblau** [comment]
Fixed by 9b82ecdd131774ac68a337b972f402b775976965
