### ISSUE TITLE
Create Comment & Header Deduper

### ISSUE THREAD

**Issue by joeblau** [joeblau/gitignore.io#439]
## Issue

When generating a template for Hugo, GitHub's template has a comment that matches the comment that gitignore.io injects for every template.   The result is a template that looks like.  The solution should be  deduplicating any comment lines in the file.

```
...
# Edit at https://www.gitignore.io/?templates=hugo

### Hugo ###
### Hugo ###
# gitginore template for Hugo projects
# website: https://gohugo.io
...
```

### Development Environment:

- [ ] Machine (Local, Container, Virtual): Local
- [ ] Operating System (Name/Version): macOS, Linux (All versions)
- [ ] Web Browser (Name/Version): All browsers
- [ ] Vapor Version: latest
- [ ] Swift Version: latest

### Expected Behavior:

A template with only one header

```
...
# Edit at https://www.gitignore.io/?templates=hugo

### Hugo ###
# gitginore template for Hugo projects
# website: https://gohugo.io
...
```
### Actual Behavior:

A template with multiple headers

```
...
# Edit at https://www.gitignore.io/?templates=hugo

### Hugo ###
### Hugo ###
# gitginore template for Hugo projects
# website: https://gohugo.io
...
```

### Reproduction Steps:

Go to: https://www.gitignore.io/api/hugo or type `gi hugo` using the command line

**Comment by djkeh** [comment]
I took a look and think it's technically possible to put a simple deduper code in:

https://github.com/joeblau/gitignore.io/blob/992611ff67af6081b60449624961308f1d920bea/Sources/App/Controllers/TemplateController.swift#L68-L76

I doubt that title in hugo template from github/gitignore wouldn't happen again and will be in the same format like, `### language ###`. But if it feels too much annoying and needs to be fixed instantly, maybe it's fine to put a simple line of code that replaces title-like lines from template file to empty strings.
