### ISSUE TITLE
Question for localizations

### ISSUE THREAD

**Issue by djkeh** [joeblau/gitignore.io#440]
Hi @joeblau,
I see localizations directory on the project root, but how am I supposed to watch them? Now I feel excited to see gitignore.io in different languages, and I'd gladly like to add Korean translations if you don't mind.

**Comment by joeblau** [comment]
What do you mean watch them?  Do you mean contribute?

**Comment by djkeh** [comment]
I mean I found `Localizations` directory on the project root and guessed gitignore.io may support localizations for some countries, but couldn't find how to see website in different languages.

**Comment by joeblau** [comment]
The localizations piece broke in a recent version of [Vapor](https://vapor.codes).  I think they are working to update how Localization works.  I'm also looking at better ways to create an entire site that supports full localization.

**Comment by djkeh** [comment]
I see. Then which way are you looking better? Waiting for the future Vapor update having localization feature fixed, or just changing the framework? A new pr #441 recently came up for Persian localization, thanks to @mshomali, but if you decide to switch Vapor, maybe I should wait to add up a new translation file.

**Comment by joeblau** [comment]
Well I'm debating between switching to a different version of vapor or hosting a static site and just using vapor as an engine.  Static site generators already have a clean way to implement localization globally (right now the docs aren't localized).  That would also let me separate the ignore template engine from the UI which is pretty much static.  I have a prototype that I've been working on, but still nothing finalized.

**Comment by djkeh** [comment]
Okay, hosting a static site sounds great as well! I'll upload Korean translation file waiting for your work. Good luck!

**Comment by joeblau** [comment]
If you want, you can create an issue for adding a Korean translation and when you have the translations we can close that issue.

**Comment by djkeh** [comment]
Sure I will!
