### ISSUE TITLE
Missing trailing new line at the end of output

### ISSUE THREAD

**Issue by brainplot** [joeblau/gitignore.io#442]
This is a very minor thing but it's kind of annoying. When calling gitignore.io from the command line, the generated output has no trailing new line at the end. I'm running Linux with zsh as my shell and by default it displays an inverse and bold `%` at the end of partial lines. When I run `gi list`, this is what the output looks like:
![before](https://user-images.githubusercontent.com/28014843/51706230-11b9ae80-201e-11e9-9359-8d05205cb16d.png)

By simply running `gi list && echo` (`echo` adds a trailing `\n`) the problem goes away:
![after](https://user-images.githubusercontent.com/28014843/51706313-5fceb200-201e-11e9-8bb0-152a56fd9407.png)

Same thing happens with the help screen:
![man](https://user-images.githubusercontent.com/28014843/51706415-a45a4d80-201e-11e9-8e17-4190cbf0951c.png)

### Expected Behavior:
Output printed with a trailing new line marking the end of the line.

### Actual Behavior:
Last line lacks of the new line character (I expect quite a few tools to warn about this, Github's diffing screens do this as well IIRC).

As a temporary fix, I put this in one of my zsh config files:
```zsh
function gi() { curl -sL https://www.gitignore.io/api/${(j:,:)@} && echo }
```

### Reproduction Steps:
1) Install zsh
2) Invoke gitignore.io's command line APIs

**Comment by joeblau** [comment]
> This is a zsh feature that prints a percent-and-newline after a command completes if that command does not already include a newline at the end of its output. If zsh did not do this, you would either not ever notice the fact that the command didn't print a newline - or you'd see zsh's command prompt not start on the margin and think it was a bug in zsh.

`curl -sLw "\n"  https://www.gitignore.io/api/` will fix it

Source: https://stackoverflow.com/questions/29497038/why-does-a-curl-request-return-a-percent-sign-with-every-request-in-zsh

**Comment by joeblau** [comment]
I updated the documentation to ensure that people with `zsh` don't see this issue.

https://docs.gitignore.io/install/command-line#masos-zsh

**Comment by MainasuK** [comment]
> I updated the documentation to ensure that people with `zsh` don't see this issue.
> 
> https://docs.gitignore.io/install/command-line#masos-zsh

I use the macOS zsh script in the Catalina but not get the correct function in ./zshrc. It looks like missing the " symbols. (zsh --version: zsh 5.7.1 (x86_64-apple-darwin19.0))

![2019-11-0112 02 24](https://user-images.githubusercontent.com/7940186/68001596-ab924400-fc9f-11e9-8b5a-6ec67b2af560.png)

Then I try to use the `'` instand of `"` with break.
![2019-11-0112 08 22](https://user-images.githubusercontent.com/7940186/68001738-4e4ac280-fca0-11e9-83b9-5d2fd25b0569.png)
 That looks works well.

```zsh
echo "function gi() { curl -sLw '\\\n' https://www.gitignore.io/api/\$@ ;}" >> \
~/.zshrc && source ~/.zshrc
```
