### ISSUE TITLE
Adding Korean translation

### ISSUE THREAD

**Issue by djkeh** [joeblau/gitignore.io#444]
# Issue Template

## Issue

This issue is for adding Korean translation file into the gitignore.io project.

## Reference

https://github.com/joeblau/gitignore.io/blob/a97c13cababb0a098dd63a9682656f8ecef31753/Localizations/en.json#L1-L15

**Comment by joeblau** [comment]
고맙습니다 
<img width="1117" alt="2019-02-12 5 55 23" src="https://user-images.githubusercontent.com/1218847/52630724-fc041000-2e8a-11e9-9d7b-25b56acaa4b6.png">

**Comment by djkeh** [comment]
This is beautiful. Thanks!

p.s: I'll look into the way to deal with that `Please enter 1 or more characters`, too, if I may :)

**Comment by joeblau** [comment]
Oh that’s part of select2.  I’ll have to make a separate localization file for that.

**Comment by djkeh** [comment]
No rush :) Please let me know if you make up your mind. If it's too bulky we can just forget it.
