### ISSUE TITLE
Remove VSCode (User) Settings

### ISSUE THREAD

**Issue by telekommander** [joeblau/gitignore.io#447]
All of them ( the forced files by `!` notation ) are user-settings and should not be a part of a repository.

```
### VisualStudioCode ###
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
```

**Comment by joeblau** [comment]
Please submit your changes to this template to GitHub and we'll sync them down once they are approved.  

https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore

Thanks.
