### ISSUE TITLE
Improve the display format of `gi list`

### ISSUE THREAD

**Issue by RobertAudi** [joeblau/gitignore.io#48]
```sh
gi() {
  local maxColumns=1
  local calculatedColumns=$(($(echo $COLUMNS | tr -d "\n") / 45))
  local columns=$(($calculatedColumns > $maxColumns ? $calculatedColumns : $maxColumns))
  local maxWidth=120
  local calculatedWidth=$(($(echo $COLUMNS | tr -d "\n") / 1.2))
  local width=$(($calculatedWidth > $maxWidth ? $calculatedWidth : $maxWidth))

  curl -s "http://www.gitignore.io/api/$@" | tr "," "\n" | pr -$columns -t -w$width
}
```

I know this is not a one-liner but the output is much more readable.

(Tested on ZSH only)

**Comment by adjohnson916** [comment]
+1 but why not just change the API output server-side, or offer a new endpoint or new parameters that will format it differently? That would be simpler and propagate to various command line and other clients more simply.

**Comment by joeblau** [comment]
@adjohnson916 that's a great idea.  If we spec out a format, I'll see what it will take to add this into the API.  We just need to be mindful that the output needs to work on all operating system terminals.

**Comment by adjohnson916** [comment]
@joeblau Something like https://www.gitignore.io/api/list?format=lines?

For all operating system support, we'd need to decide whether to include `\r` (carriage return) for Windows in addition to `\n` (newline / line feed). I'm not sure if it'd be necessary, or if so, whether user agent detection feasible, or better to just have a different param e.g. `format=rlines`?

**Comment by Xavdidtheshadow** [comment]
Yeah, `?format=json` returning an actual json list would be sweet and really portable!

**Comment by adjohnson916** [comment]
@joeblau I've implemented this, and added tests. See #160.

**Comment by adjohnson916** [comment]
@joeblau Thanks for merging!
