### ISSUE TITLE
gi is a reserved alias in PowerShell

### ISSUE THREAD

**Issue by ArtWDrahn** [joeblau/gitignore.io#71]
In PowerShell gi is the alias for get-item if someone was to use your PowerShell command they would find that it would not work as expected.  I would suggest changing the name to something else.  Such as gitignore or giti.  If PS naming standards are to be followed I'd suggest Get-GitIgnore (even though that doesn't exactly roll off the tongue).

**Comment by joeblau** [comment]
Changed this command to `gig` and updated documentation.
