### ISSUE TITLE
Symfony2 .gitignore suggestion 

### ISSUE THREAD

**Issue by kuldipem** [joeblau/gitignore.io#98]
```
# Assets and user uploads
/web/bundles/
/web/uploads/
/web/css/
/web/js/
```
I have added two last ignore directory which is generated by assetic generally and it is bundle with Symfony2 standered bundle.

**Comment by joeblau** [comment]
Is Symfony2 different than Symfony?

**Comment by joeblau** [comment]
- [ ] - Yes
- [ ] - No
- [ ] - Maybe

??

**Comment by theofidry** [comment]
It's the same. There is currently 3 versions of Symfony (1, 2 and 3). Obviously only one gitignore covering all the versions is needed, which I believe is what is doing the current symfony gitignore.

**Comment by joeblau** [comment]
Added files to `.patch` ignore
